### PR TITLE
[Enhancement Plan] Rewrite `Pref` Activity with AppCompat

### PR DESCRIPTION
**Pull request by WhiredPlanck**
`PreferenceActivity` 类现已被弃用。本 PR 开始尝试对 `Pref` 活动进行升级工作，即继承 `AppCompatActivity` 进行重构建。

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
完成了，所有功能都应该能正常使用～

**Comment by Bambooin** [comment]
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by Bambooin** [comment]
Others->Night Mode->Dark
Theme still is light, not dark.

**Comment by Bambooin** [comment]
Would be better move  "Help", "About", "Night Mode" and "Deploy" items to main activity?

The main setting activity has too few items now.

**Comment by Bambooin** [comment]
I have cherry pick your commit to new branch setting, so you can make pull request in this branch to avoid merge conflicts.

**Comment by WhiredPlanck** [comment]
> I have cherry pick your commit to new branch setting, so you can make pull request in this branch to avoid merge conflicts.

Get it. I will fix it soon.

**Comment by WhiredPlanck** [comment]
> Others->Night Mode->Dark
> Theme still is light, not dark.

Yes, I know. I have a typo in the entry values. I'll fix it soon too.

**Comment by WhiredPlanck** [comment]
> Others->Night Mode->Dark
> Theme still is light, not dark.

Yes, I know. I have a typo in the string array of the `Night Mode`'s entry values. I'll fix it soon too.

**Comment by WhiredPlanck** [comment]
> Would be better move "Help", "About", "Night Mode" and "Deploy" items to main activity?
> 
> The main setting activity has too few items now.

Well, that's something to say. After looking at designs of other apps and reading the Android Developer documents, I think it would be better to move `About` and `Help` to the options menu, and for similar reason, I moved the `Night Mode` to `Other` settings page.  `Deploy` is a important action in Trime while Google suggests to present important actions as buttons in the toolbar, so I also move `Deploy` to the toolbar.

So... the main idea why I did that is "just put the major preference items in the main settings page", which Google also suggests to do. The original design is really messy. Although I know there are too few items, I'll put more items soon. So don't worry.

**Comment by WhiredPlanck** [comment]
已在 #437 重新提交。

**Pull request closed without merging**
