### PR TITLE
Add telegram group

### LINKED ISSUE #346: 建议出tg群组

### LINKED ISSUE #1230: 增加 telegram 群组
#346 

https://t.me/trime_dev

集成 Github Notification 还需要几位仓库合作者的权限

@Bambooin @WhiredPlanck @goofyz

### PR DESCRIPTION
**Pull request by nopdan**
## Pull request

- [x] README: Add telegram group <https://t.me/trime_dev>
- [x] README: 添加贡献者 nopdan
- [x] README: 删除过时的分发渠道：酷安
- [x] README: 替换失效的 qq 群组
- [x] About: 删除过时的"修改版qq群"
- [x] About: Add telegram group <https://t.me/trime_dev>
- [x] About: 删除过时的应用市场：酷安
- [x] About: 添加应用市场：Fdroid

#### Issue tracker
Fixes will automatically close the related issues

Fixes #346
Fixes #1230

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
I don't like put the community section in README, since we already had put them in Trime app.

**Comment by nopdan** [comment]
> I don't like put the community section in README, since we already had put them in Trime app.

Sounds reasonable.

**Comment by WhiredPlanck** [comment]
@nopdan @Bambooin Speaking of documentation, shall we go back to GitHub Pages? It has been disappeared for a loong time ~.

**Review by WhiredPlanck — APPROVED** [review]

**Comment by nopdan** [comment]
支持将文档转到 github 仓库，这样可以在修改代码时同步修改

**Pull request merged**
