### PR TITLE
[Feature] Crash Log View

### PR DESCRIPTION
**Pull request by WhiredPlanck**
### Issue tracker
This PR is not to fix any known issue.

### Feature
Add a activity that has ability to show real-time logs of the application, and it can show up and export logs on app crash.

Also, some major adjustments to icon resource are applied in this PR:
- remove redundant .png icon format.
- change to more suitable icon schemes for some preferences.
- change tint property of some vector assets so system can change their color to fit Dark Mode automatically.

### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Thanks for your hard work. 

It's **very nice** for normal user to report crash to us with one simple click UI.

Crash report UI project: [Amaze](https://github.com/TeamAmaze/AmazeFileManager)

Library: https://github.com/ACRA/acra

**Comment by WhiredPlanck** [comment]
> Crash report UI project: [Amaze](https://github.com/TeamAmaze/AmazeFileManager)
> 
> Library: https://github.com/ACRA/acra

Look good ~ But should I implement with them this time?

**Comment by WhiredPlanck** [comment]
Some screenshots I forget to post in the description.

Following screenshots show what crash view look like when app on crash:
1. Show a dialog


2. Show a crash log view similar with real-time logs view, with a export button


3. Users can choose where to save the crash log file with SAF

**Comment by Bambooin** [comment]
No, you can look at #779 with your free time.

**Comment by WhiredPlanck** [comment]
@Bambooin Thanks ~

**Pull request merged**
