### PR TITLE
feat: use spotless to unify code style

### LINKED ISSUE #489: Use spotless to unify code style
**Is your feature request related to a problem? Please describe.**
Use spotless to unify code style.

### PR DESCRIPTION
**Pull request by Bambooin**
#### Issue tracker
Fixes will automatically close the related issue

Fixes #489 

#### Manual testing
- [x] Done

#### Build tasks success
Successfully running following tasks on local
- [ ] `./gradlew spotlessCheck`
- [x] `./gradlew assembledebug`

#### Code Reviews
1. Manual build and test pass
2. GitHub action lint and ci pass
3. At least one contributor review and vote
4. Can merge clean without conflicts
5. PR will be merge by rebase upstream base

### CODE REVIEW

**Comment by Bambooin** [comment]
@WhiredPlanck @tumuyan 

Hi all,

  Do you have any idea about this patch,
  kotlin rules need polish or use it's default.
  We need stick one rule in this project for unify code style.

Thanks

**Comment by Bambooin** [comment]
After this pull request is reviewed, I will add another pull request to unify all code by spotless.

**Comment by WhiredPlanck** [comment]
I think this is great ~

**Comment by tumuyan** [comment]
I haven't used Spotless before, but I think it’s good.

**Pull request merged**
