### PR TITLE
Adjust Nightly Build Settings (Pass 2)

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of pull request

#### Code of conduct
- [ ] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [ ] `make sytle-lint`

#### Build pass
- [ ] `make debug`

#### Manually test
- [ ] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Seems nightly build will create default tag, this tag will affect the release note which depends on last tag.

https://github.com/ncipollo/release-action
> An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).

If we can build nightly only when there are new commits, it's an improvement.

**Comment by WhiredPlanck** [comment]
@Bambooin The nightly build only run on schedule (specified at UTC 3:00 everyday), and only run when `develop` branch has new commit:

https://github.com/osfans/trime/blob/924a14a395adbe8615f926a2791e9869b0039a2a/.github/workflows/nightly-ci.yml#L4

https://github.com/osfans/trime/blob/924a14a395adbe8615f926a2791e9869b0039a2a/.github/workflows/nightly-ci.yml#L10

The tag only will be created when we specify one or the value of `github.ref` is 'refs/tags/<tag_name>'.

**Comment by Bambooin** [comment]
> The tag only will be created when we specify one or the value of github.ref is 'refs/tags/<tag_name>'.

I mean release.yml, such that when we decide to release `v3.2.17` tag, then the last tag is `nightly` instead of `v3.2.16`.

https://github.com/osfans/trime/blob/30cb7c0d8d7e158dff44742ad3cba17dbb7b7200/.github/workflows/release-ci.yml#L70-L81

**Comment by WhiredPlanck** [comment]
> > The tag only will be created when we specify one or the value of github.ref is 'refs/tags/<tag_name>'.
> 
> I mean release.yml, such that when we decide to release `v3.2.17` tag, then the last tag is `nightly` instead of `v3.2.16`.
> 
> https://github.com/osfans/trime/blob/30cb7c0d8d7e158dff44742ad3cba17dbb7b7200/.github/workflows/release-ci.yml#L70-L81

Just remove `nightly` tag, the new nightly configuration should not create a tag on the release.

**Review by Bambooin — APPROVED** [review]

**Comment by WhiredPlanck** [comment]
Hm, I'm too optimistic. If we don't specify tag or there is no valid git ref, the build will end up with failure. https://github.com/WhiredPlanck/trime-new/actions/runs/7600515837

**Comment by Bambooin** [comment]
So we have to find the workaroud on the nightly build without tag.

**Comment by WhiredPlanck** [comment]
> So we have to find the workaroud on the nightly build without tag.

@Bambooin Great news: I just find that [mikepenz/release-changelog-builder-action](https://github.com/mikepenz/release-changelog-builder-action#advanced-workflow-specification) actually has a input option called `ignorePreReleases`. Since we will publish nightly build as a prerelease, it will be useful here.

P.S. Before I discovered this option, I was struggling to write bash scripts to ignore the nightly tag when to generate the changelog, which was a wasted effort :rofl: .

**Review by Bambooin — APPROVED** [review]

**Pull request merged**
