### PR TITLE
Keyboard Refactor 20240720

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

This PR is mainly to improve the code quality, the main change is migrating KeyboardSwitcher features into KeyboardWindow.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
**Note that** KeyboardView.kt is just linted by spotless to reduce the intents after removing `@JvmOverloads` annotation. The actual change is few.

**Comment by Bambooin** [comment]
NPE crash on Firefox when keyboard pops up.

```
--------- Crash stacktrace
java.lang.NullPointerException
        at com.osfans.trime.ime.keyboard.KeyboardWindow.switchKeyboard$lambda$11(KeyboardWindow.kt:149)
        at com.osfans.trime.ime.keyboard.KeyboardWindow.$r8$lambda$_R5ZgIyTL-CpcvC4H4FHr7ZCCJo(Unknown Source:0)
        at com.osfans.trime.ime.keyboard.KeyboardWindow$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7924)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by WhiredPlanck** [comment]
@Bambooin ~I cannot reproduce. Does this issue come up frequently?~

**UPDATED:** After changing to another theme, I can reproduce it now.

**Comment by WhiredPlanck** [comment]
@Bambooin Fixed in https://github.com/osfans/trime/pull/1432/commits/916df77ae612471fffa04da6fb445e1252b7d0ea

**Review by Bambooin — APPROVED** [review]

**Pull request merged**
