### PR TITLE
Refactors to LiquidKeyboard

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A
(I will link later if there are issues are related)

#### Feature
Describe features of this pull request

Refactors to LiquidKeyboard, improve the code quality, fix bugs and enhance the UX.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

#### Additional Info
**Preview**
图片

Unfortunately, the operation area is unable to customize at this moment, I'd like to pull another request to done that.

### CODE REVIEW

**Comment by Bambooin** [comment]
The `返回` will input `liquid_keyboard_exit` in tongwenfeng theme.

**Comment by WhiredPlanck** [comment]
> The `返回` will input `liquid_keyboard_exit` in tongwenfeng theme.

Known issue. It's really confusing ......

**Comment by WhiredPlanck** [comment]
@Bambooin Fixed. Just work™.

**Review by Bambooin — APPROVED** [review]
No issue found, it's would be better if we use `英文` as the default keyborad instead of `特殊`.

**Comment by WhiredPlanck** [comment]
> No issue found, it's would be better if we use `英文` as the default keyborad instead of `特殊`.

Will done in the future.

**Pull request merged**
