### PR TITLE
Fix some bugs since v3.2.10

### LINKED ISSUE #869: 自定义主题 3.2.9 LiquidKeyboard 两侧有奇怪的空白
这是 3.2.8 的样子：

这是 3.2.9 的样子：

并且 3.2.9 返回普通键盘之后，候选栏右侧也出现奇怪的空白：

### LINKED ISSUE #895: 键盘按键倒圆角 取消了？
版本信息
Builder: Pull Request CI
Build Time: 2022-12-25 06:08 UTC
Build Version Name: v3.2.9-51-g812bea5d
Git Hash: 812bea5d
Git Branch: 894/merge
Git Repo: https://github.com/osfans/trime

新版本好像取消了键盘按键倒圆角？如下图 
Screenshot_2022-12-25-15-05-15-467_com android browser

### LINKED ISSUE #901: 似乎同文输入法不再适合非程序员使用了。
反观 小狼毫／鼠须管／中州韵 每隔几年更新一次，非常稳定。
同文是不是可以区分升级通道？让愿意进行测试的程序员可以经常在 github 上下载到最新版本，普通受众可以在 play 商店／f-droid 下载并且使用【**经过测试的，出厂可用的**】稳定版本？其实普通受众并不求时常更新，稳定才是最重要的，哪怕是几年升级一次，不要让用户战战兢兢地点按【**更新**】按钮，可以吗？

在 f-driod 商店下载的 3.2.10 居人无法设置键盘高度，原有的 trime.custom.yaml 失效也就算了，但键盘高度只能适合婴儿的小手指，让成年人如何使用？发布之前测试过了吗？还是发布后让普通用户扮演小白鼠做测试？？

抱歉，我不是程序员，我也没有参与软件测试的意愿，但无论如何，忠言逆耳，作者的更新策略的确是太过激进，激进到只剩下愿意参与测试的一小撮程序员了。

谢谢。

### LINKED ISSUE #906: 部署一直闪退，发现每隔几秒就会生成WARNING
如图，文件大小都是285B，内容就是
`W0106 08:12:59.197836 59768 registry.cc:16] replacing previously registered component: charset_filter`
image

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
- restore disappear key round corners (fixes #895)
- parse color values from inputted map first to get drawable
- initialize key sound related stuffs on storage permission granted
- add detection of whether the custom file has modified to determine whether to redeploy the theme (fixes #901 #902 )
- make sure sound package configs are showed in the picker
- don't specify log dir since we don't really need the log files (fixes #906 partially)
- eliminate the wired padding on the either side of liquid keyboard (fixes #869)
- make sure trime can play custom key effect (enhance custom sound theme management with [kaml](https://github.com/charleskorn/kaml) as well)

#### Feature
update social media information:
update the join code and api link of QQ group 2, since the original group has been dismissed for some reasons.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
@Bambooin Done.

**Comment by WhiredPlanck** [comment]
@Bambooin Done.

**Comment by tao659** [comment]
这个版本，点击输入框，都会进入数字键盘模式，而不是字母键盘模式

**Comment by WhiredPlanck** [comment]
@tao659 我这里未能复现

**Comment by WhiredPlanck** [comment]
@tao659 我这里未能复现

**Comment by tao659** [comment]
最新更新的版本https://github.com/osfans/trime/actions/runs/3872195547
无法弹出键盘，部署没报错，实时日志没报错

**Comment by WhiredPlanck** [comment]
@tao659 可我这里什么事情都没有 …… 我甚至为了测试都卸载重装过一轮了 :rofl:

**Comment by WhiredPlanck** [comment]
@tao659 可我这里什么事情都没有 …… 我甚至为了测试都卸载重装过一轮了 :rofl:

**Comment by WhiredPlanck** [comment]
@Bambooin I think here are all the bugs I can fix this time. Ready for review.

**Comment by tao659** [comment]
> @tao659 可我这里什么事情都没有 …… 我甚至为了测试都卸载重装过一轮了 🤣

最新的pr 已经解决了无法弹出键盘的问题👍🏻

**Comment by WhiredPlanck** [comment]
@tao659 @Bambooin Many thanks to you ~

**Pull request merged**
