### PR TITLE
Adapt for Android 13

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issue

Fixes # N/A

#### Feature

Groovy is a dynamic programming language, which is hard to debug in the IDE. So let's go with KTS.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
@Bambooin This PR is ready for review.

**Comment by WhiredPlanck** [comment]
@Bambooin This PR is ready for review.

**Comment by Bambooin** [comment]
Still got an error with `make release`, and the version number was updated in `develop` branch.

```
* What went wrong:
Execution failed for task ':app:packageRelease'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > SigningConfig "release" is missing required property "storeFile".
```

**Comment by WhiredPlanck** [comment]
> Still got an error with `make release`, and the version number was updated in `develop` branch.
> 
> ```
> * What went wrong:
> Execution failed for task ':app:packageRelease'.
> > Multiple task action failures occurred:
>    > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
>       > SigningConfig "release" is missing required property "storeFile".
>    > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
>       > SigningConfig "release" is missing required property "storeFile".
>    > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
>       > SigningConfig "release" is missing required property "storeFile".
>    > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
>       > SigningConfig "release" is missing required property "storeFile".
> ```

What the compiler says before this PR? Have you provided the store file?

**UPDATE:** Reproduced. Will fix it soon.

**Comment by WhiredPlanck** [comment]
@Bambooin d171ef9 should fix the issue you mentioned.

**Comment by Bambooin** [comment]
Found one error with `make release`.

```
Execution failed for task ':app:lintVitalRelease'.
>                 Lint found fatal errors while assembling a release target.

                  Fix the issues identified by lint, or create a baseline to see only new errors:
                  ```
                  android {
                      lint {
                          baseline = file("lint-baseline.xml")
                      }
                  }
                  ```

                  For more details, see https://developer.android.com/studio/write/lint#snapshot

                  ~/github/trime/app/build.gradle.kts:72: Error: Google Play requires that apps target API level 31 or higher.
   [ExpiredTargetSdkVersion]
          targetSdk =  29
          ~~~~~~~~~~~~~~~

     Explanation for issues of type "ExpiredTargetSdkVersion":
     As of the second half of 2018, Google Play requires that new apps and app
     updates target API level 26 or higher.
```

**Comment by WhiredPlanck** [comment]
@Bambooin This may be not the fault of this PR, our `targetSdkVersion` is really too low. It's time to update it.

We updated the dependencies and compile sdk version at 2994bfe, those new version of dependencies require compile sdk version 32/33 or higher, and this version requires higher target sdk version to build release.

**UPDATE:** I've checked out to previous commit and find that building will be successful...... This really confuse me. Need to take time to investigate.

**Comment by WhiredPlanck** [comment]
@Bambooin It seems that in kts format, the compiler will enforce to check if the targetSdkVersion is expired. We may need to explicitly suppress or disable the check or just update the targetSdkVersion.

**Comment by WhiredPlanck** [comment]
@Bambooin LGTM

图片

**Comment by linsui** [comment]
This somehow breaks F-Droid build. In the old code the exec function fallbacks to an empty string but now it fails directly.  Some commands fail in F-Droid's CI.

```
+ git config user.name
+ echo failed
failed
+ git describe --tags --long --always
v3.2.12-0-g31fa50fd
+ git rev-parse --short HEAD
31fa50fd
+ git symbolic-ref --short HEAD
fatal: ref HEAD is not a symbolic ref
+ echo failed
failed
+ git remote get-url origin
https://github.com/osfans/trime
```

**Pull request merged**
