### PR TITLE
Add memory leak detection library

### PR DESCRIPTION
**Pull request by WhiredPlanck**
# Pull request

## Feature
Add leakcanary Version 2.9.1. leakcanary is a memory leak detection library for Android. 

That’s it, there is no code change needed!
Ref: https://github.com/square/leakcanary

## Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

## Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

## Manual test
- [x] Done

## Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

## Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
One concern, we only have debug in Github release.

So many user will have some performance and battery issue.

**Comment by WhiredPlanck** [comment]
> One concern, we only have debug in Github release.
> 
> So many user will have some performance and battery issue.

Don't worry, LeakCanary is just a lightweight plugin that watching the critical instances (like activities, services ......), which will not make a big impact on the performance. Fairly I really don't think our app usually should to blame for battery issues while some "small and pretty" apps are draining our battery and even the privacy.

**Comment by WhiredPlanck** [comment]
I also find two other libraries may be more helpful:

- https://github.com/iqiyi/xCrash
- https://github.com/KwaiAppTeam/KOOM

**Comment by WhiredPlanck** [comment]
I give up this PR for I finally feel this library is helpless for our project ......

**Pull request closed without merging**
