### PR TITLE
Refactors 20240930

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

This PR is mainly to improve the code quality.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by goofyz** [comment]
Issue #1463 comes back in this commit.

**Comment by WhiredPlanck** [comment]
@goofyz ~~https://github.com/osfans/trime/pull/1478/commits/7983955b0b1ca5fbda38ce086bd040a89133454c~~ https://github.com/osfans/trime/pull/1478/commits/70fa9d918d50116946c746749d8b66402e230913 may fix it.

**Comment by goofyz** [comment]
第一次啟動時還是只會用 default keyboard.
要到「方案」選取一次後才能用回 schema id keyboard.
不過此問題可能跟此 PR 無關。根據 https://github.com/osfans/trime/issues/1463#issuecomment-2367667577 的描述應該上次的 pr 也有此問題。

**Comment by WhiredPlanck** [comment]
> 第一次啟動時還是只會用 default keyboard. 要到「方案」選取一次後才能用回 schema id keyboard. 不過此問題可能跟此 PR 無關。根據 [#1463 (comment)](https://github.com/osfans/trime/issues/1463#issuecomment-2367667577) 的描述應該上次的 pr 也有此問題。

打了日志看过了，要匹配键盘的时候 `schemaItemCached` 已经能得到及时同步了 ……

**Comment by WhiredPlanck** [comment]
@goofyz 如果没其他问题，我就先合并了。我这里确实无法复现 #1463 的问题。

**Review by goofyz — APPROVED** [review]

**Comment by WhiredPlanck** [comment]
@goofyz Force push to make slight refactors. Never mind.

**Pull request merged**
