### PR TITLE
fix: uncaught exception #657

### LINKED ISSUE #657: uncaught exception caused crash using jiugong
java.lang.ArrayIndexOutOfBoundsException: length=30; index=-1
AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
AndroidRuntime: 	at com.osfans.trime.ime.text.Candidate.onCandidateClick(Candidate.java:166)

Candidate.java:166
`ComputedCandidate candidate = computedCandidates.get(index);`

### PR DESCRIPTION
**Pull request by InfinityLoop1308**
#### Issue tracker
Fixes will automatically close the related issue

Fixes #657 

#### Feature
Describe feature of pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Exception is for exception only

In this case, we should check the **root cause of index equals to -1**

If we can't avoid index be invalid, we can check index is among [0, candidate.size()]

```
if(index>=0 && index < computedCandidates.size()) {
  // normal process 
}
```

**Comment by InfinityLoop1308** [comment]
> Exception is for exception only
> 
> In this case, we should check the **root cause of index equals to -1**
> 
> If we can't avoid index be invalid, we can check index is among [0, candidate.size()]
> 
> ```
> if(index>=0 && index < computedCandidates.size()) {
>   // normal process 
> }
> ```

You are right. New commit is added.

**Comment by Bambooin** [comment]
Code style check seems fail, would you mind squash you commit to one?

./gradlew spotlessCheck

**Comment by InfinityLoop1308** [comment]
> Code style check seems fail, would you mind squash you commit to one?
> 
> ./gradlew spotlessCheck
Fixed. Since this branch is too messy, I will raise a new PR.

**Pull request closed without merging**
