### PR TITLE
Introduce setup wizard

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Feature
Introduce a setup wizard to make new user happy.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
According to the feedback from QQ Group Community，I may need to polish it more. So I convert this as draft.

**Comment by Bambooin** [comment]
After add `Skip` button, the `Next` and `Done` button is out of scope

Would you mind rebase upstream to fix conflict and force push?

**Comment by WhiredPlanck** [comment]
> After add `Skip` button, the `Next` and `Done` button is out of scope

Wired, this doesn't appear on my device (pad).

> Would you mind rebase upstream to fix conflict and force push?

I will rebase on upstream to resolve the conflics.

**Comment by WhiredPlanck** [comment]
@Bambooin I'm sorry for that I have no other device for some reason to test the setup wizard layout. Would you like to help me test if the problem has been fixed? Thanks ~!

**Comment by Bambooin** [comment]
Done, layout is ok now

**Pull request merged**
