### PR TITLE
chore(CI): add JNI cache

### PR DESCRIPTION
**Pull request by iovxw**
## Pull request

Cache the prebuilt

#### Issue tracker
Fixes will automatically close the related issue

Fixes #

#### Feature
Describe feature of pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by iovxw** [comment]
The saved cache size of all PR will be 0, which is fine, caches generated by PR is useless

See https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

**Comment by iovxw** [comment]
Okay...not fine, edited, not 0 now

And the fail is expected (We can not remove the previous 0 sized cache), this PR is ready for merge

**Comment by iovxw** [comment]
If you want see the result of this PR: https://github.com/iovxw/trime-1/runs/4242255476

**Comment by Bambooin** [comment]
Thanks for your amazing work, build time decrease about 87.89%(from 1140s to 138s)

- move cache-hash.sh to script folder
- add `app/build.gradle` to `JNI_FILES` as it contain `ndkVersion` and `cmake`
- add cache to release-ci.yml workflow
- don't burn the midnight oil, the rime community needs you

PS: Sleep well, work well

**Comment by iovxw** [comment]
Done

**Pull request merged**
