### PR TITLE
增加草稿箱管理器

### LINKED ISSUE #510: 自动缓存文本框输入的内容（草稿/draft）
## 问题背景
如果用户关闭了编辑框，或者退出App，再次打开时可能文本框内容就被清空了。
关闭编辑框、退出App的行为可能是用户主动执行的——我在做这样的动作前，如果需要缓存，过去使用fv抽取文本，现在使用同文剪切文本，然后文本就会自动保存到列表中。再次打开可以选择并粘贴。  
但是这类行为也可能是误操作，或者程序异常。（比如网络异常发送失败，但是文本框也被错误清空了）

## 解决方案
这应该是任何Android应用都还没有的一个功能，我打算做一下：  
当弹出输入法键盘，以及commit文字时，输入法缓存当前文本框的文字。
在输入法软键盘弹出或隐藏时，自动保存之前编辑的文本内容到一个列表中。（为了避免缓存数量过多，可以设置符合什么样的正则表达式就不缓存。如果此次键盘弹出和上次键盘收起内容相同）
再次打开文本框，用户需要恢复现场，可以在输入法liquidKeyboard中打开“草稿/draft”，从列表中选择一个缓存进行commit

## 进度
已经复制剪贴板的代码实现了基本功能

### PR DESCRIPTION
**Pull request by tumuyan**
#### Issue tracker
Fixes #510 

#### Feature
Add new feather: Draft
在唤起和隐藏键盘时，自动缓存文本框的内容。代码基本从剪贴板管理器复制而来，与剪贴板管理器一起显示在liquidKeyboard中。
默认皮肤已经添加了草稿箱的功能。

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
How to delete all draft and clipboard contents, not one by one?

We need an manager for this two features: delete, update, delete all and auto clear old entry...

LGTM for code, but lack of function.

**Comment by Bambooin** [comment]
Is there any way to disable this feature in the setting?

`Draft` and `Clipboard` may contain something very privacy and secret password....

**Comment by tumuyan** [comment]
> Is there any way to disable this feature in the setting?
> 
> `Draft` and `Clipboard` may contain something very privacy and secret password....

Setting - others - draft manager/ clipboard manager could select disable


> We need an manager for this two features: delete, update, delete all and auto clear old entry...

Of cause we need the function, but it takes a lot of work.
These tasks are already in the todo list #464 , but no progress at the moment

**Comment by Bambooin** [comment]
Would you mind replace variable name and table name for draft?

Copy and paste is ok but with right variable name please

```
    db.delete("t_clipboard", "text=?", new String[] {clipboardBean.getText()});
    db.execSQL(
        "insert into t_clipboard(text,html,type,time) values(?,?,?,?)",
        new Object[] {
          clipboardBean.getText(),
          clipboardBean.getHtml(),
          clipboardBean.getType(),
          clipboardBean.getTime()
        });
```

**Comment by tumuyan** [comment]
> Would you mind replace variable name and table name for draft?

Now the table name of draft and clipboard is same as `t_data`. (Also they use the same bean and dbhelper)

**Comment by Bambooin** [comment]
It seem will keep password and other important secret in draft

We should exclude password enable input text before keep it draft

My phone unlock password is in draft, and I can't delete now

If I used bank app, my bank password and payment code will keep too?

PS: need more people review and test

**Comment by tumuyan** [comment]
> It seem will keep password and other important secret in draft
> 
> We should exclude password enable input text before keep it draft
> 
> My phone unlock password is in draft, and I can't delete now
> 
> If I used bank app, my bank password and payment code will keep too?
> 
> PS: need more people review and test

yes, pw should exclude. I will update the code to avoid 

Actually I use these draft filter:

```
.{1,12}
.{800,}
http([^\s]*)
```

**Comment by tumuyan** [comment]
> It seem will keep password and other important secret in draft
> 
> We should exclude password enable input text before keep it draft
> 
> My phone unlock password is in draft, and I can't delete now
> 
> If I used bank app, my bank password and payment code will keep too?

Now a texteditor with those InputType will not trigger the draft manager

```
TYPE_TEXT_VARIATION_EMAIL_ADDRESS, 
TYPE_TEXT_VARIATION_PASSWORD, 
TYPE_TEXT_VARIATION_VISIBLE_PASSWORD, 
TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS, 
TYPE_TEXT_VARIATION_WEB_PASSWORD, 

```

**Comment by ameaninglessname** [comment]
如何清空草稿箱和剪贴板？

这里也有个相关的issue #686

**Comment by InfinityLoop1308** [comment]
> 如何清空草稿箱和剪贴板？
> 
> 这里也有个相关的issue #686

see PR #793

**Comment by ameaninglessname** [comment]
> > 如何清空草稿箱和剪贴板？
> > 这里也有个相关的issue #686
> 
> see PR #793

Thank you!

**Pull request merged**
