### PR TITLE
multi: introduce multiple improvements

### PR DESCRIPTION
**Pull request by WhiredPlanck**
## Purpose
Reorganize or rewrite original methods, fix known problems or improve the performance.

## Progress
- [x] 1. Reorganize/rewrite/introduce some classes in multiple packages.
- [x] 2. More detailed files categories.
- [x] 3. Reduce the warnings, make the code more effective.

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
### Secondary Progress
1. - [x] New/Optimized API-methods manager.
2. - [x] Move classes to their packages.
3. - [x] Standard code writing.

#### Third Progress
1. - [x] `TrimeKeyEffects.kt` (to replace `Effect.java`)
    - [x] `Speech.java`
    - [x] `KeyboardManager.kt` (to replace`KeyboardSwitch.java`)
2. - [x] `Speech.java` -> ime.core.`Speech.java`
    - [x] `xScrollView.java` -> ime.text.`xScrollView.java`
    ......
3. - [x] `Speech.java`
    - [x] `IntentReceiver.java`
    - [x] `Config.java` (partly)
    - [x] `xScrollView.java`  
    ......

**Comment by tumuyan** [comment]
我觉得按键音效/振动称为feedback更加合适。
effect一般讲特效，比如让按键产生立体视觉效果，水晶效果，上划下滑移动轨迹的描绘，手写输入的笔锋，按键按下的动画效果

**Comment by ameaninglessname** [comment]
感觉这两个词都可以,角度不一样: 效果描述它们本身,反馈是站在用户角度描述它们

有些行业,把特效special effect统称为FX, 分为视效visual effects (VFX) ,音效sound effects (SFX) ...等等

**Comment by WhiredPlanck** [comment]
@Bambooin This PR could be merged.

**Comment by Bambooin** [comment]
Thanks for your hard work, refactor is very polish!

**Comment by Bambooin** [comment]
By the way, it better to rebase upstream change instead of merge, and confilct can be fixed in rebase.

**Comment by WhiredPlanck** [comment]
Sorry for that...... I don't figure out how to rebase or merge better, thanks for your appreciation.

**Pull request closed without merging**
