### PR TITLE
Improve Works of the Views Handling

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Review by nopdan — APPROVED** [review]

**Review by goofyz — APPROVED** [review]

**Comment by nopdan** [comment]
从没有设置 enter_labels 的主题切换到有 enter_labels 的主题，第一次显示键盘时 enter 键的 label 会变为空

**Comment by nopdan** [comment]
bug: 悬浮窗宽度不会自动增加

**Comment by WhiredPlanck** [comment]
> bug: 悬浮窗宽度不会自动增加

已修复

**Comment by tao659** [comment]
从这个版本开始出现#1247 bug
一直到2.18的版本

**Pull request merged**
