### PR TITLE
Use External Prebuilt Artifacts

### LINKED ISSUE #953: [Dev] Use prebuilt dependencies
**Is your feature request related to a problem? Please describe.**
Currently we've added the git repositories of the dependencies (like boost, glog, leveldb ......) of librime and OpenCC as the project's submodules to build with the app. Since they rarely change but version update, we can prebuild those artifacts to speed up the building and reduce the code base, just like [what fcitx5-android does](https://github.com/fcitx5-android/prebuilt). And actually we've done [similar works](https://github.com/osfans/trime/blob/b978f3a907134488fc716987cd41b5a701a014dd/.github/workflows/pull-request-ci.yml#L55).

**Describe the solution you'd like**
I'd like to setup a prebuilder to build the dependencies and release it to a place, such as GitHub Release, so that we can get a permalink to download the artifacts and utilize them. And I've done [some works](https://github.com/WhiredPlanck/trime-prebuilt).

**Describe alternatives you've considered**
N/A

**Additional context**

cc @Bambooin

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #953 

#### Feature
Describe features of pull request

Use External Prebuilt Artifacts

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by tao659** [comment]
闪退 错误报告如下

ava.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found: needed by /data/app/~~VSXfa5N9242w0moc3cV5Mw==/com.osfans.trime.debug-jee6rPOfIN_1Uu9CjRYxKQ==/lib/arm64/libiconv.so in namespace classloader-namespace
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.osfans.trime.core.Rime.<clinit>(Rime.kt:60)
	at com.osfans.trime.ui.main.PrefMainActivity$onOptionsItemSelected$1$2.invokeSuspend(PrefMainActivity.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fed89ae, Dispatchers.Main.immediate]

**Comment by WhiredPlanck** [comment]
@tao659 e120fb5 应该解决了此问题，请再尝试一次

**Comment by tao659** [comment]
> @tao659 [e120fb5](https://github.com/osfans/trime/commit/e120fb5607ea0ed1af72b3858b10f52c367e1071) 应该解决了此问题，请再尝试一次

新版没有此问题了，👍🏻

**Comment by Bambooin** [comment]
This pull request will split Trime code to two different repos?

For contributors, they have to use two repos: https://github.com/WhiredPlanck/trime-prebuilt

**Comment by WhiredPlanck** [comment]
> This pull request will split Trime code to two different repos?
> 
> For contributors, they have to use two repos: https://github.com/WhiredPlanck/trime-prebuilt

@Bambooin No need actually, modified `CMakeLists.txt` will download the artifacts **(NOT clone the source)** from the prebuilt repo's Release (in the case here, it downloads from my own repo), i.e. any contributors just need to make their way to get the prebuilt artifacts.  And in theory, anyone could create their own prebuilt artifacts, just build them correctly by NDK and let them comply the certain kind of file tree structure.

**Comment by WhiredPlanck** [comment]
@Bambooin I realize that this may block the build on F-Droid buildbots, since F-Droid requires build everything from source ......

**Comment by Bambooin** [comment]
We should keep the only live F-Droid channel for distribution, since the Google channel is obsolete.

**Pull request closed without merging**
