### PR TITLE
[WIP] Clean code and fix deployment

### LINKED ISSUE #334: 同步/部署会崩溃: NullPointerException, Config.getSharedDataDir()
这是同步的日志, 部署也是 `NullPointerException`

```log
03-22 09:47:43.982 I/ActivityManager(22499): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.osfans.trime/.Pref (has extras)} from uid 10303
03-22 09:47:44.037 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/android.widget.FrameLayout com.osfans.trime/android.widget.FrameLayout
03-22 09:47:44.089 I/ActivityManager(22499): Start proc 6170:com.osfans.trime/u0a307 for activity com.osfans.trime/.Pref
03-22 09:47:44.353 I/ActivityManager(22499): Displayed com.osfans.trime/.Pref: +370ms
03-22 09:47:44.359 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/com.osfans.trime.Pref com.osfans.trime/com.osfans.trime.Pref
03-22 09:47:44.520 W/SurfaceFlinger(751): Attempting to set client state on removed layer: Splash Screen com.osfans.trime#0
03-22 09:47:44.520 W/SurfaceFlinger(751): Attempting to destroy on removed layer: Splash Screen com.osfans.trime#0
03-22 09:47:45.849 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/android.app.Dialog com.osfans.trime/android.app.Dialog
03-22 09:47:50.347 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/com.osfans.trime.Pref com.osfans.trime/com.osfans.trime.Pref
03-22 09:48:03.061 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/com.osfans.trime.Pref com.osfans.trime/com.osfans.trime.Pref
03-22 09:48:03.076 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/com.osfans.trime.Pref com.osfans.trime/com.osfans.trime.Pref
03-22 09:48:03.398 W/SurfaceFlinger(751): Attempting to set client state on removed layer: thumbnail anim: AppWindowToken{a805c2 token=Token{13d020d ActivityRecord{bd064a4 u0 com.osfans.trime/.Pref t8616}}}#0
03-22 09:48:03.399 W/SurfaceFlinger(751): Attempting to destroy on removed layer: thumbnail anim: AppWindowToken{a805c2 token=Token{13d020d ActivityRecord{bd064a4 u0 com.osfans.trime/.Pref t8616}}}#0
03-22 09:48:04.007 D/ActivityInfoProvider(22338): setLatestComponent: com.osfans.trime/android.app.Dialog com.osfans.trime/android.app.Dialog
03-22 09:48:04.632 E/Pref    (6170): Sync Exceptionjava.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.osfans.trime.Config.getSharedDataDir()' on a null object reference
03-22 09:48:04.636 D/SurfaceFlinger(751): duplicate layer name: changing com.osfans.trime/com.osfans.trime.Pref to com.osfans.trime/com.osfans.trime.Pref#1
03-22 09:48:04.652 W/InputDispatcher(22499): channel '5bb9333 com.osfans.trime/com.osfans.trime.Pref (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-22 09:48:04.652 E/InputDispatcher(22499): channel '5bb9333 com.osfans.trime/com.osfans.trime.Pref (server)' ~ Channel is unrecoverably broken and will be disposed!
03-22 09:48:04.655 W/InputDispatcher(22499): channel '6cfe8e9 com.osfans.trime/com.osfans.trime.Pref (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-22 09:48:04.656 E/InputDispatcher(22499): channel '6cfe8e9 com.osfans.trime/com.osfans.trime.Pref (server)' ~ Channel is unrecoverably broken and will be disposed!
03-22 09:48:04.657 I/ActivityManager(22499): Process com.osfans.trime (pid 6170) has died: fore TOP 
03-22 09:48:04.657 W/ActivityManager(22499): Force removing ActivityRecord{bd064a4 u0 com.osfans.trime/.Pref t8616}: app died, no saved state
03-22 09:48:04.661 I/WindowManager(22499): WIN DEATH: Window{6cfe8e9 u0 com.osfans.trime/com.osfans.trime.Pref}
03-22 09:48:04.661 W/InputDispatcher(22499): Attempted to unregister already unregistered input channel '6cfe8e9 com.osfans.trime/com.osfans.trime.Pref (server)'
03-22 09:48:04.668 I/WindowManager(22499): WIN DEATH: Window{5bb9333 u0 com.osfans.trime/com.osfans.trime.Pref}
03-22 09:48:04.668 W/InputDispatcher(22499): Attempted to unregister already unregistered input channel '5bb9333 com.osfans.trime/com.osfans.trime.Pref (server)'
03-22 09:48:04.669 W/SurfaceFlinger(751): Attempting to set client state on removed layer: com.osfans.trime/com.osfans.trime.Pref#1
03-22 09:48:04.669 W/SurfaceFlinger(751): Attempting to destroy on removed layer: com.osfans.trime/com.osfans.trime.Pref#1
```

第一次使用即如此, 即使重新安装也如此

```
Android 9
trime 3.1.3-20190930
rime 1.5.3-8-g3b5dbf6-arm64-v8a
```

### PR DESCRIPTION
**Pull request by cognition9144**
- [x] Fix #334 
- [x] Try **not** to avoid `context` to maintain state. Fixes some complicated crashes and avoid undiscovered bugs.
- [x] `setup()` before calling APIs (AFAIK it should only take place in init phase, however the data model and JNI are harder to understand than I expected.
- [ ] Fix schema_get_value JNI.
````
3-23 22:30:00.257 20124 20285 F om.osfans.trim: runtime.cc:630]   native: #12 pc 00000000001a6d50  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (rime::Deployer::Run()+172)
03-23 22:30:00.258 20124 20285 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20285 (Thread-3), pid 20124 (om.osfans.trime)
03-23 22:30:00.528 20288 20288 F DEBUG   : pid: 20124, tid: 20285, name: Thread-3  >>> com.osfans.trime <<<
03-23 22:30:00.536 20288 20288 F DEBUG   :       #06 pc 00000000000071bc  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime_jni.so (on_message(void*, unsigned long, char const*, char const*)+68) (BuildId: 4e5c5681def4d54a8d629b97ba254c9880a80344)
03-23 22:30:00.536 20288 20288 F DEBUG   :       #07 pc 0000000000255edc  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (rime::Service::Notify(unsigned long, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+140) (BuildId: 29195cd89ea0d5f7154837740d587fc350bbe90b)
03-23 22:30:00.536 20288 20288 F DEBUG   :       #08 pc 00000000001aa43c  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (_ZNK5boost8signals26detail20slot_call_iterator_tINS1_21variadic_slot_invokerINS1_9void_typeEJRKNSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEESD_EEENS5_15__list_iteratorINS_10shared_ptrINS1_15connection_bodyINS5_4pairINS1_15slot_meta_groupENS_8optionalIiEEEENS0_4slotIFvSD_SD_ENS_8functionISO_EEEENS0_5mutexEEEEEPvEEST_E11dereferenceEv+88) (BuildId: 29195cd89ea0d5f7154837740d587fc350bbe90b)
03-23 22:30:00.536 20288 20288 F DEBUG   :       #09 pc 00000000001a99e4  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (boost::signals2::detail::signal_impl<void (std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&), boost::signals2::optional_last_value<void>, int, std::__ndk1::less<int>, boost::function<boost::signals2::optional_last_value>, boost::function<boost::signals2::optional_last_value><void (boost::signals2::connection const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)>, boost::signals2::mutex>::operator()(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+536) (BuildId: 29195cd89ea0d5f7154837740d587fc350bbe90b)
03-23 22:30:00.536 20288 20288 F DEBUG   :       #10 pc 00000000001a6d50  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (rime::Deployer::Run()+172) (BuildId: 29195cd89ea0d5f7154837740d587fc350bbe90b)
03-23 22:30:00.536 20288 20288 F DEBUG   :       #11 pc 00000000001ab544  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (BuildId: 29195cd89ea0d5f7154837740d587fc350bbe90b)
03-23 22:30:00.537 20288 20288 F DEBUG   :       #12 pc 00000000001ab5f8  /data/app/com.osfans.trime-vhi_C3DjoS2fZ_APkPjKmQ==/lib/arm64/librime.so (BuildId: 29195cd89ea0d5f7154837740d587fc350bbe90b)
03-23 22:30:00.967  1468 20291 W ActivityTaskManager:   Force finishing activity com.osfans.trime/.Pref
03-23 22:30:01.023  1468  1989 W InputDispatcher: channel '80c8137 com.osfans.trime/com.osfans.trime.Pref (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-23 22:30:01.023  1468  1989 E InputDispatcher: channel '80c8137 com.osfans.trime/com.osfans.trime.Pref (server)' ~ Channel is unrecoverably broken and will be disposed!
03-23 22:30:01.030  1468  1989 W InputDispatcher: channel '213134e com.osfans.trime/com.osfans.trime.Pref (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-23 22:30:01.030  1468  1989 E InputDispatcher: channel '213134e com.osfans.trime/com.osfans.trime.Pref (server)' ~ Channel is unrecoverably broken and will be disposed!
03-23 22:30:01.032  1468  4725 I ActivityManager: Process com.osfans.trime (pid 20124) has died: vis+99 TOP 
03-23 22:30:01.033  1468  2443 I WindowManager: WIN DEATH: Window{213134e u0 com.osfans.trime/com.osfans.trime.Pref}
03-23 22:30:01.033  1468  2443 W InputDispatcher: Attempted to unregister already unregistered input channel '213134e com.osfans.trime/com.osfans.trime.Pref (server)'
````

### CODE REVIEW

**Comment by osfans** [comment]
还剩下一个？要不要先merge？

**Comment by cognition9144** [comment]
Sorry I don't have much time this week. Next week will be fine. 

There are some fatal bugs. It may not be wise to merge for now (in case someone download the generated apk).

**Comment by cognition9144** [comment]
However, if it's ok for dev builds, maybe you can merge it before it diverge from `master` too much.

**Comment by cognition9144** [comment]
OK I did some work to make it at least better than before (need to deploy twice). You may merge now.

**Pull request merged**
