### PR TITLE
Reproducible build and Release build

### LINKED ISSUE #1078: 支持release打包
尝试支持release打包，大佬帮忙看看是否可行？谢谢

1、添加release.keystore（.gitignore需要去掉）并且修改app/build.gradle.kts中的storeFile
```
 storeFile = rootProject.file("release.keystore")
```
2、workflows中release-ci.yml Setup keystore步骤大致如下，使用github action secrets存储密钥
```
      - name: Setup keystore
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        run: |
          touch keystore.properties
          echo storePassword="$SIGNING_STORE_PASSWORD" > keystore.properties
          echo keyPassword="$SIGNING_KEY_PASSWORD" >> keystore.properties
          echo keyAlias="$SIGNING_KEY_ALIAS" >> keystore.properties
```
3、release-ci.yml Build Trime 步骤修改为`make release`
4、release-ci.yml Add JNI cache 步骤`debug`修改为`release`

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1078

#### Feature
Describe features of pull request

Please merge #1173 first.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Please only keep commit 5881669681ad7e89944c92b842d6cecdbbfa6393 in this pull request.

Seems you forgot to check out new branch from origin/develop in this pull request.

**Comment by WhiredPlanck** [comment]
@Bambooin I didn't expect osfans's sudden reply, so I make this PR direly based on #1173 for quick respond.

**Comment by Bambooin** [comment]
LGTM

How to verify the release build?
1. Merge and create new tag(3.2.17)
1. Create your own secret in your repo and create test tag to verify

**Review by Bambooin — APPROVED** [review]

**Comment by WhiredPlanck** [comment]
> LGTM
> 
> How to verify the release build?
> 
>     1. Merge and create new tag(3.2.17)
> 
>     2. Create your own secret in your repo and create test tag to verify

I prefer the second method. But I think we can also create a release candidate (rc)，just create a pre-release.

**Comment by WhiredPlanck** [comment]
Forced push to ~~https://github.com/osfans/trime/pull/1174/commits/524604a469d857a9ad2c1457bbbcc9924a65b192~~ https://github.com/osfans/trime/pull/1174/commits/43cd234495cbade3541b4665914ec3bfc47a94ed to change the step of native cache hash calculating.

**Comment by WhiredPlanck** [comment]
@Bambooin Test great: https://github.com/WhiredPlanck/trime-new/releases/tag/v3.2.17-rc2

**Pull request merged**
