### PR TITLE
core: add a helper to organize SharedPreferences

### PR DESCRIPTION
**Pull request by WhiredPlanck**
## Also
- add `AndroidUtilCode` implementation to get frequently used methods.
- use a custom Application class.

## Progress
- [x] Added the helper class.
- [x] Unified related Preference items `key` naming style.
- [x] Created a custom Application class to help apply the global helper.
- [x] Apply the helper class.

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
@Bambooin This PR could be merge now ~

**Comment by ameaninglessname** [comment]
By the way, when will next version release?

**Comment by WhiredPlanck** [comment]
> By the way, when will next version release?

Wow, you reply so fast, friend ~ :smile: 

But actually I have no idea with new version release, it mostly depends on how many issues we have fixed or how many new features we have added. 

Unfortunately, we haven't made much progress in either of these two (I think). So at least there is no new version *this mouth*.

**Comment by WhiredPlanck** [comment]
> By the way, when will next version release?

Maybe I could build a test version and release on my fork page, so you could install it to enjoy. I'll give it a try ~

**Comment by WhiredPlanck** [comment]
> By the way, when will next version release?

You could go to [here](https://github.com/WhiredPlanck/trime-new/releases/tag/3.2.1%2Bgit20210805) to test the app~

**Comment by Bambooin** [comment]
- Go to Preferences->Sound on keypress | Vibrate on key press
- It will have no sound or vibrate except restart app.

**Comment by WhiredPlanck** [comment]
>     * Go to Preferences->Sound on keypress | Vibrate on key press
> 
>     * It will have no sound or vibrate except restart app.

I haven't got the key name under the `onSharedPreferenceChanged` method in the `KeyboardFragment.kt` refactored, so the effect doesn't be retested immediately. I'll fix it in next PR.

**Pull request merged**
