### PR TITLE
Data sync fix

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Found some issues:
- The opencc was duplicated in `rime/opencc` and `shared/opencc` which will lead larger apk
- Reset failed with toast
- Add end of line to files within `.idea` folder

**Comment by WhiredPlanck** [comment]
> Found some issues:
> 
>     * The opencc was duplicated in `rime/opencc` and `shared/opencc` which will lead larger apk
> 
>     * Reset failed with toast
> 
>     * Add end of line to files within `.idea` folder

1. Actually apk will only contains the newest assets, since we don't rename the destination path, this will not occupy the duplicated storage space.
2. Fixed.
3. Fixed.

**Comment by Bambooin** [comment]
This is the unpacked folder from apk, and the latest apk is 9.2MB.

```
$ ls -lh trime2024090*
-rw-r--r-- 1  8.8M Sep  1 09:40 trime20240901.apk
-rw-r--r-- 1  8.8M Sep  2 20:05 trime20240902.apk
-rw-r--r-- 1  8.8M Sep  3 20:46 trime20240903.apk
-rw-r--r-- 1  8.8M Sep  5 22:02 trime20240905.apk
-rw-r--r-- 1  8.8M Sep  7 21:53 trime20240907.apk
-rw-r--r-- 1  9.2M Sep  8 16:17 trime20240908.apk
```

Duplicated assets with `make release`, due to `opencc-data` target in Makefile, so do we need to remove this target?

```
tree  rime/ shared/
rime/
└── opencc
    ├── hk2s.json
    ├── hk2t.json
    ├── HKVariantsRevPhrases.txt
    ├── HKVariantsRev.txt
    ├── HKVariants.txt
    ├── jp2t.json
    ├── JPShinjitaiCharacters.txt
    ├── JPShinjitaiPhrases.txt
    ├── JPVariants.txt
    ├── s2hk.json
    ├── s2t.json
    ├── s2tw.json
    ├── s2twp.json
    ├── STCharacters.txt
    ├── STPhrases.txt
    ├── t2hk.json
    ├── t2jp.json
    ├── t2s.json
    ├── t2tw.json
    ├── TSCharacters.txt
    ├── TSPhrases.txt
    ├── tw2s.json
    ├── tw2sp.json
    ├── tw2t.json
    ├── TWPhrasesRev.txt
    ├── TWPhrases.txt
    ├── TWVariantsRevPhrases.txt
    ├── TWVariantsRev.txt
    └── TWVariants.txt
shared/
├── default.yaml
├── key_bindings.yaml
├── opencc
│   ├── hk2s.json
│   ├── hk2t.json
│   ├── HKVariantsRevPhrases.txt
│   ├── HKVariantsRev.txt
│   ├── HKVariants.txt
│   ├── jp2t.json
│   ├── JPShinjitaiCharacters.txt
│   ├── JPShinjitaiPhrases.txt
│   ├── JPVariants.txt
│   ├── s2hk.json
│   ├── s2t.json
│   ├── s2tw.json
│   ├── s2twp.json
│   ├── STCharacters.txt
│   ├── STPhrases.txt
│   ├── t2hk.json
│   ├── t2jp.json
│   ├── t2s.json
│   ├── t2tw.json
│   ├── TSCharacters.txt
│   ├── TSPhrases.txt
│   ├── tw2s.json
│   ├── tw2sp.json
│   ├── tw2t.json
│   ├── TWPhrasesRev.txt
│   ├── TWPhrases.txt
│   ├── TWVariantsRevPhrases.txt
│   ├── TWVariantsRev.txt
│   └── TWVariants.txt
├── punctuation.yaml
├── symbols.yaml
├── tongwenfeng.trime.yaml
└── trime.yaml

```

**Comment by WhiredPlanck** [comment]
> Duplicated assets with `make release`, due to `opencc-data` target in Makefile, so do we need to remove this target?

No need to remove. Just rename “rime” to “shared” in the target dir. I forgot to change there.

**Comment by WhiredPlanck** [comment]
@Bambooin Done.

**Review by Bambooin — APPROVED** [review]
LGTM, verified with manually testing.

**Pull request merged**
