### PR TITLE
Utilize New Config Parser on Theme

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of pull request

Utilize New Config Parser on Theme.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Keyboard can't be shown up in Android 11.

**Comment by wxyzh** [comment]
> Keyboard can't be shown up in Android 11.


@WhiredPlanck 
If the `qwerty` keyboard is not defined in `preset_keyboards`, it may crash when show keyboard.

**Comment by WhiredPlanck** [comment]
@Bambooin @wxyzh Commit 2acc322 and 35cc9f7 may fix the issue.

**Comment by Bambooin** [comment]
There are lots of crash and misbehavior with Trime theme in the latest patch.

**Comment by WhiredPlanck** [comment]
@Bambooin Sign ... Theme is really hard to refactor or improve. May you paste a part of the crash log here?

**Comment by WhiredPlanck** [comment]
@Bambooin This PR may be too radical to pull. I'd like to wait a more appropriate time.

**Pull request closed without merging**
