### PR TITLE
ci: upload arm64_v8a apk and librime_jni.so artifacts

### PR DESCRIPTION
**Pull request by tumuyan**
## Pull request
为commit ci增加保存的artifacts

#### Issue tracker
Fixes will automatically close the related issue

Fixes #

#### Feature
1. 单独保存commit-ci编译的arm64-v8a APK（目前最普遍使用的ABI），减少下载开销。
2. 保存commit-ci编译的librime_jni.so，方便本地无法编译成功jni的人获取到最新elf文件。

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
3. Manual build and test pass
4. GitHub action ci pass
5. At least one contributor reviews and votes
6. Can be merged clean without conflicts
7. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
No need for armv8 artifact.

Lack new line end of file.

**Comment by tumuyan** [comment]
> No need for armv8 artifact.

always user don't need download all these artifacts. why not provide artifact only contains armv8?

**Comment by tumuyan** [comment]
@Bambooin  换行符已经补上。

1. 下载编译结果压缩包后，用户往往只试用其中一个APK文件，不愿意甚至也不能测试多个ABI。
2. 在目前的Android设备中，ARM64v8A毫无疑问是最普遍的
3. 允许用户直接下载只包含ARM64版本的APK，可以节约用户的流量和磁盘空间，得到更好的测试体验。
4. 当前网络大环境，国内用户下载更小的文件有更高的成功率
**综上所述，提供单独包含arm64v8a的编译结果压缩包，是有必要的**。况且这是一个给用户的选择，原有包含全部APK的压缩包也还会继续存在。我不理解你到底是考虑了什么？

**Comment by Bambooin** [comment]
Can we only build armv8 artifactory?

I will change the commit message.

**Comment by tumuyan** [comment]
Sorry I undo and force push with a wrong commit info.
I think we should provide these artifacts  for someone who use a x86 device , emulator, or others device which couldn't run armv8a

**Pull request merged**
