### PR TITLE
Improvment for Liquidkeyboard and Database 

### PR DESCRIPTION
**Pull request by WhiredPlanck**
## Issue tracker
None

## Feature
Improve some code logic of LiquidKeyboard, and migrate the databases to [AndroidX Room](https://developer.android.com/training/data-storage/room), refactor related code and allow users to manage the clipboard, collection and draft data just on the keyboard.

Also there is a minor improvement for permission request of the app.

**Warning**: Because of the migration of the databases, the LiquidKeyboardActivity who has managed the databases before is temporarily unavailable, and I doesn't workaround a perfect way to utilize it again, so I just keep it there along with the old database stuffs. 

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
Preview

[liquid2.webm](https://user-images.githubusercontent.com/47623588/196041855-bf0afdd6-aa84-45af-ab53-0daa0c7837ee.webm)

**Comment by Bambooin** [comment]
Used a few days with this patch, thanks for your hard work.

Can we add `Delete all items` function?

Found one issue with `tongwenfeng` theme and `Lost Temple` color, the board will be invisible.

invisible

**Comment by WhiredPlanck** [comment]
> Can we add `Delete all items` function?

Oh, of course. I almost forgot that. I will add it soon.

**Comment by WhiredPlanck** [comment]
> Found one issue with `tongwenfeng` theme and `Lost Temple` color, the board will be invisible.

I forgot to set the key text color, just need to one line code to fix.

**Comment by WhiredPlanck** [comment]
@Bambooin Done.

**Pull request merged**
