### PR TITLE
Basic Adaption to Android 14

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by nopdan** [comment]
tg 群友测试
image

**Comment by WhiredPlanck** [comment]
> tg 群友测试 image

最新的提交应该修了这个问题

**Review by goofyz — APPROVED** [review]
I think we should use `WorkManager` rather than `exactAlarm` in the next version.

**Comment by WhiredPlanck** [comment]
> I think we should use `WorkManager` rather than `exactAlarm` in the next version.

I'm not sure. It's said that `WorkManager` cannot work well on some ROMs like MIUI.

**Review by nopdan — APPROVED** [review]

**Pull request merged**
