### PR TITLE
修复迷你键盘不自动收起的问题；尝试修复悬浮窗问题；优化一点代码

### LINKED ISSUE #1126: 关于悬浮窗，希望能有更多的人进行测试一下
我在使用的时候，发现悬浮窗的位置（left, right, left_up, right_up）不对，大概表现为始终在屏幕的最左侧，y方向上大致是对的。

使用的是3.2.15版本。

于是我就好奇，对代码debug了一下。然后发现那部分的代码我其实不太能看懂。但大概位置是：

https://github.com/osfans/trime/blob/7e9b4ef65df41c74ff965b0c9b3d6d98aa0f2692/app/src/main/java/com/osfans/trime/ime/core/Trime.java#L179C7-L208

我不太明白的点在于那频繁的min和max。而且再上面一些，一开始取maxX的时候，我debug出来的值也不对（是一个负值，例如-500）。

所以，我就暴力的做了一些删除，把else分支里面的min, max全部删掉之后。再进行了测试。

在我的设备上（vivo Pad），悬浮窗口的位置是正确的了。

所以我不确定，大家是否也在悬浮窗口这里有问题，希望大家能够进行更多一些的测试。也希望开发大佬们，能够把这里的代码梳理一下，看是否有一些疑似适配的问题。

### PR DESCRIPTION
**Pull request by cabins**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1126 

#### Feature
- 修复迷你键盘不自动收起的问题，原因xml中一个key写错了；
- 尝试修复悬浮窗问题（需要更多人进行测试一下）；
- 优化一点代码（没有改逻辑，优化了一下之前一位大佬的写法）

#### Code of conduct
- [ ] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [ ] `make sytle-lint`

#### Build pass
- [ ] `make debug`

#### Manually test
- [ ] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Trigger the CI build manually, so others can download and verify this fix.

CI is failed due to spotless check: Run `./gradlew :spotlessApply` to fix these violations.

It's nice to use the commit message template such as:
- fix: fix float window size limit
- fix: fix mini keyboard auto hiding

Thanks for your hard work to fix the issue and debug: #930

**Comment by Bambooin** [comment]
If you have time, please squash or rebase your commits to two parts:

- fix: fix float window size limit
- fix: fix mini keyboard auto hiding

If you don't have free time, it's ok right now, waiting for code review.

**Comment by tao659** [comment]
Screenshot_2023-12-01-06-17-45-459_com miui notes-edit
显示异常如图所示。

**Comment by cabins** [comment]
> Screenshot_2023-12-01-06-17-45-459_com miui notes-edit 显示异常如图所示。


Emmm……这就是我担心的适配问题。因为我手里只有vivo的设备，所以我测试了手机(Origin OS 4 based on Android 14)以及vivo Pad Air（Origin OS 3 based on Android 13)。看样子，这里真的是有适配问题。

待进一步排查。

**Comment by cabins** [comment]
> If you have time, please squash or rebase your commits to two parts:
> 
>     * fix: fix float window size limit
> 
>     * fix: fix mini keyboard auto hiding
> 
> 
> If you don't have free time, it's ok right now, waiting for code review.

Thank you so much for all recent guidances. I learned so much about debugging, creating pr, git-using and code style.

Proud of all trime contributors.

**Pull request merged**
