### PR TITLE
Add fastlane metadata for F-Droid

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

Add fastlane metadata for F-Droid and update Android Gradle Plugin.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Review by Bambooin — APPROVED** [review]
Can we use the new release to verify this patch?

**Comment by WhiredPlanck** [comment]
> Can we use the new release to verify this patch?

I think it will be OK.

**Comment by WhiredPlanck** [comment]
@Bambooin I want to fix a bug (related to #1354 #1356 ), don't hurry, I will do soon.

**Comment by WhiredPlanck** [comment]
I'll merge this PR first, and the PR to fix the bug will come later.

**Comment by Bambooin** [comment]
We have nightly release, so the specific fix can be put in next release cadence.

**Comment by WhiredPlanck** [comment]
> We have nightly release, so the specific fix can be put in next release cadence.

OK

**Pull request merged**
