### PR TITLE
UI and data improvement

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
- Fix the issue where schemas sometimes failed to be enabled.
- Fix the issue where "Sync in background" preference never show the time and status of last sync.

Note that "Sync user data" (called "Synchronize" previously) usually doesn't work, which need further investigation.

#### Feature
A lot of refactors and improvement for UI and data handling, including:
- Reorganize the preference screen.
  - Use ViewModel to share data among the fragments. 
  - Use a main Activity for all main fragments, and navigated by AndroidX Navigation component.
  - Change some preference name.
- Polish the translations.
- Improve the code logic of those picker dialog.
- Move app UI-related code into `ui` directory.
- Improve implementation of some UI components. 
- Split and improve some functions of data handling.

In addition:
- set source and target compatibility as Java 8
- ~~enable desugaring to enable support for new language APIs, which allow to include more standard language APIs in apps that support older versions of Android without requiring a minimum API level for your app.~~ Due to the worries about the compatibility, disable desugaring temporarily. 

#### 问题跟踪
- 修复方案偶尔启用失败的问题。
- 修复“后台同步”设置项从未显示上次同步时间和状态的问题。

注意，“同步”功能通常无法工作（通常会失败），需要进一步调查。

#### 功能
大量对用户界面和数据处理的重构和改进，包括：
- 重新组织了设置页面。
  - 使用 ViewModel 在各个 fragments 之间共享数据。
  - 一个主 Activity 对应众多主要 fragments，并使用 AndroidX 的导航组件导航。
  - 更改了一些设置项的名称。
- 翻译润色。
- 改进众多对话框的代码逻辑。
- 将应用 UI 相关的代码移入 `ui` 文件夹下。
- 改进了一些 UI 组件的实现。
- 细化和改进了一些数据处理的功能。

此外：
- 设定源码和目标兼容性为 Java 8。
- ~~启用[“脱糖”](https://developer.android.com/studio/write/java8-support-table)以启用对新语言 API 的支持，可以支持在较低 Android 版本的应用中添加更多标准语言 API，而无需提高应用的最低 API 级别。~~ 出于对兼容性的担忧，暂时禁用“脱糖”。

### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

### Manual test
- [x] Done

### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
It seems that the translation is still not pretty satisfying. It may be necessary to polish again.

**Comment by WhiredPlanck** [comment]
> It seems that the translation is still not pretty satisfying. It may be necessary to polish again.

After polish:

**Comment by Bambooin** [comment]
Thanks for your hard working, setting menu is more clear now.

Found some regression issues:

1. `About` ==> `Build info` is empty.
2. `Profile` ==> `Reset` missing three items.

Prefer choose to reset specific file.

**Comment by Bambooin** [comment]
Code style:

Please move `def nav_version = "2.4.2"` to version section.

**Comment by WhiredPlanck** [comment]
@Bambooin Done

**Comment by Bambooin** [comment]
Found a crash issue:

```
E/CustomActivityOnCrash( 6636): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash( 6636): 	at java.lang.Class.classForName(Native Method)
E/CustomActivityOnCrash( 6636): 	at java.lang.Class.forName(Class.java:454)
E/CustomActivityOnCrash( 6636): 	at java.lang.Class.forName(Class.java:379)
E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(tfCustomActivityOnCrash.java:177)
E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
E/CustomActivityOnCrash( 6636): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/CustomActivityOnCrash( 6636): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CustomActivityOnCrash( 6636): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
E/CustomActivityOnCrash( 6636): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash( 6636): 	... 10 more
```

How to reproduce it:
1. Install [Shelter](https://github.com/PeterCxy/Shelter)
2. Install Trime to Shelter
3. Open Firefox in Shelter and try to input something
4. Trime crash and failed to show keyboard

**Comment by Bambooin** [comment]
https://github.com/google/desugar_jdk_libs

Do we really need this, I prefer to remove this dependency.

Seem this lib causes crash with compatibility issue.

**Comment by WhiredPlanck** [comment]
> https://github.com/google/desugar_jdk_libs
> 
> Do we really need this, I prefer to remove this dependency.
> 
> Seem this lib causes crash with compatibility issue.

I think it may be necessary, since there are a lot of Java code in this project, desugaring will save a lot of time for developing, because it allows us use new and handy language APIs without increasing the minimum API level. 

KDE Connect also enables desugaring and its minimum API level is 14, I think the compatibility issue may caused by other things.

**UPDATE**: I find that I forgot to enable multiDex, which required by desugaring to increase the compatibility. Let me enable it and look if crash will disappear.

**Comment by WhiredPlanck** [comment]
> Found a crash issue:
> 
> ```
> E/CustomActivityOnCrash( 6636): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
> E/CustomActivityOnCrash( 6636): 	at java.lang.Class.classForName(Native Method)
> E/CustomActivityOnCrash( 6636): 	at java.lang.Class.forName(Class.java:454)
> E/CustomActivityOnCrash( 6636): 	at java.lang.Class.forName(Class.java:379)
> E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
> E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
> E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(tfCustomActivityOnCrash.java:177)
> E/CustomActivityOnCrash( 6636): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
> E/CustomActivityOnCrash( 6636): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
> E/CustomActivityOnCrash( 6636): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
> E/CustomActivityOnCrash( 6636): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
> E/CustomActivityOnCrash( 6636): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
> E/CustomActivityOnCrash( 6636): 	... 10 more
> ```
> 
> How to reproduce it:
> 
>     1. Install [Shelter](https://github.com/PeterCxy/Shelter)
> 
>     2. Install Trime to Shelter
> 
>     3. Open Firefox in Shelter and try to input something
> 
>     4. Trime crash and failed to show keyboard

It seems that it don't crash in Firefox on my Android 10 device now.

**Comment by Bambooin** [comment]
Latest commit failed on Shelter with Android 11.

Same error with class not found.

https://github.com/google/desugar_jdk_libs/blob/master/README.md
`This is not an official Google product.`

We'd better avoid using library desugar, this library usage is **very rare**

JDK is already too complex, so let's Google cares about the compatibility issue.

**Comment by WhiredPlanck** [comment]
> We'd better avoid using library desugar, this library usage is **very rare**

Hm, I've seen that a branch of applications add this in their dependencies, and according to https://developer.android.google.cn/studio/write/java8-support#library-desugaring, it's documented.

**Comment by WhiredPlanck** [comment]
> Latest commit failed on Shelter with Android 11.

Cannot reproduce with Android 11 in emulator.

**UPDATE**: I uploaded the package from Actions to QQ group and several members reported that they cannot reproduce this issue too.

**Comment by Bambooin** [comment]
Install Trime in Shelter, it will **only crash in Shelter**.

In the normal installation, it's fine.

**Comment by WhiredPlanck** [comment]
> Install Trime in Shelter, it will **only crash in Shelter**.

How about previous version of Trime? I think this issue may caused by Work Profile mechanism. I cannot even install Trime into Shelter in the emulator and my physical device......

**Comment by Bambooin** [comment]
They always work except this patch.

The crash begins at this patch.

You can try your native work profile.

**Comment by WhiredPlanck** [comment]
> They always work except this patch.
> 
> The crash begins at this patch.
> 
> You can try your native work profile.

Let me take time to investigate ~

**Comment by WhiredPlanck** [comment]
> They always work except this patch.
> 
> The crash begins at this patch.
> 
> You can try your native work profile.


Sorry, but I still cannot install the app into Work Profile even via `adb`. I tried to disable desugaring but it didn't help ...... I have really no idea about this issue as for now.

**UPDATE**: I manage to install the app into Work Profile just now, but I cannot see its launcher icon......

**Comment by WhiredPlanck** [comment]
Here is a apk package which I disable desugaring to build, would you like to help to test if it fix that issue? @Bambooin 

https://envs.sh/QqR.apk (This is a file hosting link powered by envs.net, don't worry.)

**Comment by Bambooin** [comment]
Seem the apk uploaded by you is broken. I can't install to Shelter.

**Comment by Bambooin** [comment]
Found the root cause of the crash, see #816

https://developer.android.com/guide/topics/manifest/activity-alias-element

All activities must be declared above <activity-alias> tag.

Would you mind refactor and rebase your code.

1. Move activities above <activity-alias> tag.
2. Remvoe the `desugar_jdk_libs` part.
3. Rebase your change.

**Comment by WhiredPlanck** [comment]
> 2\. Remvoe the `desugar_jdk_libs` part.

I afraid that we cannot perform this on/after this PR because I've enabled desugaring and utilized the new Stream API of Java 8 to refactor some code to increase readability, etc.

**Comment by WhiredPlanck** [comment]
@Bambooin It seems that you really don't agree to enable desugaring, so I've disabled it and refactor the places where use Stream APIs.

**Pull request merged**
