### PR TITLE
ui: support set navigation bar color following the activity or window

### LINKED ISSUE #293: 底部导航栏颜色适配
如谷歌输入法在使用时 底部导航栏与输入法界面都为白色 更有一体感
Screenshot_20190603-235734
Screenshot_20190603-235724
不知能否让输入法根据配色方案自适配或由用户选择导航栏颜色?

开发辛苦了

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issue

Fixes #293 

#### Manual testing
- [x] Done

#### Build tasks success
Successfully running following tasks on local
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembledebug`

#### Code Reviews
1. Manual build and test pass
2. GitHub action lint and ci pass
3. At least one contributor review and vote
4. Can merge clean without conflicts
5. PR will be merge by rebase upstream base

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
看起来 spotless 会对一些为了阅读方便而加的空格和换行敏感

**Comment by walk143** [comment]
> 看起来 spotless 会对一些为了阅读方便而加的空格和换行敏感

line-220:此种行尾注释导致缩进失败

image

**Comment by Bambooin** [comment]
We should stick to the rule, or it would be a nightmare to resolve merge conficts.

**Comment by Bambooin** [comment]
Spotless rule can fixed by `./gradlew spotlessApply`

AS and others IDE have spotless plugin to help it.

**Comment by WhiredPlanck** [comment]
> Spotless rule can fixed by `./gradlew spotlessApply`
> 
> AS and others IDE have spotless plugin to help it.

Thanks ~

**Pull request merged**
