### PR TITLE
Bug fix 20241207

### LINKED ISSUE #1516: Cannot type `{`, `}`, `(`, `)` in nightly
### 摘要 / Summary

Cannot type `{`, `}`, `(`, `)` in nightly

### 重现步骤 / Steps to Reproduce

1. Type `{`, `}`, `(`, `)`
2. Nothing happened

### 预期行为 / Expected Behavior

Type `{`, `}`, `(`, `)` successfully

### 日志 / Log

_No response_

### 截图 / Screenshot

_No response_

### 附加信息 / Additional Context

_No response_

### 系统版本 / OS Version

15

### 应用版本 / App Version

Nightly

### 构建信息 / Build Information

Builder: Nightly CI
Build Time: Nov 26, 2024 00:24:03

### LINKED ISSUE #1518: Nightly版本使用实体键盘的时候，Enter键会输入一个空格或TAB之类的空白符，而不是回车
### 摘要 / Summary

① 这个现象在很多的程序里面都能复现，比如浏览器的地址栏，或者平板系统里面的一些搜索栏，甚至笔记软件
② 为了排除方案配置的影响，我测试的时候使用了空白的方案，即没有任何配置，也能复现这个问题
③ 我测试了Nightly，3.3.1，3.3.0这三个版本发现，3.3.0是正常的，从3.3.1开始就已经不正常了，具体的Commit未知

### 重现步骤 / Steps to Reproduce

如上面描述

### 预期行为 / Expected Behavior

预期是输入回车的表现，实际输入的是一个空格或者TAB之类的空白符号

### 日志 / Log

_No response_

### 截图 / Screenshot

_No response_

### 附加信息 / Additional Context

_No response_

### 系统版本 / OS Version

14

### 应用版本 / App Version

nightly-0-g9e1969b2-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：9e1969b2b67f4d05696b14a08728c7654b9aab80
构建时间：2024年11月28日 00:23:45

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1518
Fixes #1516 

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
@goofyz @Bambooin All done.

**Comment by goofyz** [comment]
#1524 still is not fixed

**Comment by WhiredPlanck** [comment]
> #1524 still is not fixed

Hm, some users in QQ group tell me it's OK ……

**Comment by WhiredPlanck** [comment]
> #1524 still is not fixed

I remove the link to #1524 , let me pull another request to figure it out.

**Review by goofyz — APPROVED** [review]

**Pull request merged**
