### PR TITLE
Bug fix 20240901

### LINKED ISSUE #1454: 普通键盘无法直出非 ASCII 字符
### 摘要 / Summary

当前普通键盘能直接输出（即不通过输入法）的字符只有 ASCII 字符，非 ASCII 字符按了没反应。所以类似同文风主题中的符号、标点键盘都无法使用。但液态键盘没这问题

### 重现步骤 / Steps to Reproduce

1. 切换至「同文风」主题；
2. 按一下【⌘】；
3. 随便按按里面的标点、表情什么的；
4. 你会发现只有 ASCII 范围的内容有输出，其他没反应。

### 预期行为 / Expected Behavior

非 ASCII 字符应当按原样输出。

### 日志 / Log

_No response_

### 截图 / Screenshot

_No response_

### 附加信息 / Additional Context

_No response_

### 系统版本 / OS Version

HarmonyOS 4（Android 12 兼容）

### 应用版本 / App Version

v3.2.19-47-g54de6557-release

### 构建信息 / Build Information

构建者：Windy Deng
Git 仓库：https://github.com/osfans/trime.git
构建 Git 哈希：54de65570436c31255e42047aed5ad9fcc8f1512
构建时间：2024 年 9 月 1 日 19:41:29

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1454 

#### Feature
Describe features of this pull request

Quick bug fix for recent changes.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
The inital issue in #1454 was fixed, another issue found, we can't input two same non-ASCII characters.

- 'aa' the second fails
- 'aba' is ok

**Comment by WhiredPlanck** [comment]
@Bambooin Fixed.

**Comment by goofyz** [comment]
In Chinese mode, 

"AAA" -> ok
"aaa" -> ok
"aaaAAA" -> only "aaa" will appear, "AAA" will not be displayed.  However, "AA" will appear immediately if "Backspace" is pressed.

And "Shift" in Chinese mode will remains "On" for a single click.  Is it the default behaviour?

**Comment by WhiredPlanck** [comment]
> In Chinese mode,
> 
> "AAA" -> ok "aaa" -> ok "aaaAAA" -> only "aaa" will appear, "AAA" will not be displayed. However, "AA" will appear immediately if "Backspace" is pressed.
> 
> And "Shift" in Chinese mode will remains "On" for a single click. Is it the default behaviour?

No sure for this, I just restore the oringinal logic of this

**Comment by WhiredPlanck** [comment]
> "aaaAAA" -> only "aaa" will appear, "AAA" will not be displayed. However, "AA" will appear immediately if "Backspace" is pressed.

Fixed.

**Comment by Bambooin** [comment]
In non-ASCII mode, no non-ASCII(such as emoji) characters can be inputed.

In ASCII mode, every thing is fine.

**Comment by WhiredPlanck** [comment]
@Bambooin Fixed.

**Review by Bambooin — APPROVED** [review]
LGTM, I verified all cases in this pull request, it's working right now.

**Comment by WhiredPlanck** [comment]
@Bambooin OK, I'd like to fix a glitch about the unrolled candidates then merge this.

**Pull request merged**
