### PR TITLE
Multiplatform Build Support

### LINKED ISSUE #575: Enable matrix build in Github Action
Our current ci build support only Linux, we need add macOS and Windows.

### LINKED ISSUE #1010: 请问各位大佬rime编译不通过是怎么回事？
image

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes #1010
Fix #575 

#### Feature
Describe features of pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [x] `make sytle-lint`

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Fix #575

**Comment by WhiredPlanck** [comment]
@Bambooin Done.

**Comment by Bambooin** [comment]
- We should split spotless check to one job.

- Use os-latest instead of ubuntu-22.04

- The latest runner image has ndk and cmake with android setup job, so remove ndk job? 

https://github.com/actions/runner-images

**Comment by WhiredPlanck** [comment]
> * We should split spotless check to one job.
> 
>     * Use os-latest instead of ubuntu-22.04
> 
>     * The latest runner image has ndk and cmake with android setup job, so remove ndk job?
> 
> 
> https://github.com/actions/runner-images

I reference [the job steps from fcitx5-android](https://github.com/fcitx5-android/fcitx5-android/blob/b0b2590bb2191be589d14bf873e8f17a0c5a668e/.github/workflows/pull_request.yml#L11). IMO, the version of those toolkits (or their setups) bundled in runner-images may not be the latest, or not enough convenient / reasonable. So some jobs may still make sense there.

About the fixed runner-image versions, I think they probably have the following considerations: 

- With fixed versions of runner images, the CI process becomes more predictable. The same set of tests is run every time code is committed, and the outcomes are expected to be the same. This predictability makes it easier to identify when a build fails and why it fails, thus speeding up the debugging process. 
- It ensures that developers are testing their code on a consistent platform. This consistency allows for repeatable builds and tests, which in turn ensures that any issues are not masked or caused by differences in hardware, operating systems, or software versions.

**Comment by Bambooin** [comment]
I checked the all os latest tag at noon, and find the cmake is good enough for us.

The latest tag was upgraded by GitHub, so we won't need to change it later.

The ndk and cmake are bundled with android setup action too, the ndk job is duplcated.

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#android

https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#android

https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#android

**Comment by WhiredPlanck** [comment]
@Bambooin Hm, OK, I will improve the job steps soon. ~But there is one more thing: I find `cache-hash.sh` actually doesn't work on Windows (even specify the shell as Bash), but I have no idea with its PoweShell version. I may need help.~

**UPDATED**: It actually works. Never mind.

**Comment by Bambooin** [comment]
We use gradle wrapper, so no need gralde setup job?

**Comment by WhiredPlanck** [comment]
> We use gradle wrapper, so no need gralde setup job?

@Bambooin Action's author gives answers: [Why use the `gradle-build-action`?](https://github.com/gradle/gradle-build-action#why-use-the-gradle-build-action)

**Pull request merged**
