### PR TITLE
feat: impl autofill inline API

### LINKED ISSUE #1090: feature request: 支持密码管理器输入法内嵌填充
**Describe the solution you'd like**

诸如 BitWarden、KeePassDX 之类的密码管理器可以和支持密码内联的输入法（如 Gboard）进行联动，快捷输入密码，如下图所示

Screenshot_2023-10-18-21-56-09-901_org mozilla firefox

由于 Android 系统的碎片性，如果不使用输入法内联方案的话，密码管理器的磁帖不一定能百分百调起，所以希望可以支持输入法密码内嵌填充

**Additional context**

参考 Gboard

### PR DESCRIPTION
**Pull request by ShellWen**
#### Feature
Trying to implement the autofill inline API for better interoperability with password managers, etc.  
Please refer to Issues #1090 for details.  
The implementation is still in progress, and this PR is for tracking progress and communication of the implementation.

#### Code of conduct
- [ ] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [ ] `make sytle-lint`

#### Build pass
- [ ] `make debug`

#### Manually test
- [ ] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

#### Additional Info
Close #1090

### CODE REVIEW

**Comment by ShellWen** [comment]
@Bambooin 目前的实现主要存在的问题是似乎目前并没有做 inline suggestions？目前我没有找到办法在键盘上显示相关的建议，我平时主要在 Linux 上使用 rime，对 trime 了解不是很多

**Comment by ShellWen** [comment]
这里可以找到一些参考：https://developer.android.com/reference/androidx/autofill/inline/v1/InlineSuggestionUi

**Comment by MokOopsing** [comment]
fcitx5-android上有类似功能，建议参考下

**Comment by goofyz** [comment]
I saw that u changed `Trime.java` to kotlin.  I suggested u to extract that into a simplier PR and merged first.  Otherwise it may be difficult to merged later as it involved too many functionality.

**Comment by ShellWen** [comment]
> I saw that u changed `Trime.java` to kotlin. I suggested u to extract that into a simplier PR and merged first. Otherwise it may be difficult to merged later as it involved too many functionality.

I will cherry pick later. Thanks for your advice.

**Comment by AdoKevin** [comment]
这个有进展了吗？ 
I'm really looking forward to this。

**Comment by eric1ee** [comment]
> 这个有进展了吗？ I'm really looking forward to this。

我也一直在等这个功能，真的很需要

**Comment by linzianabc** [comment]
这个有进展了吗？

**Pull request closed without merging**
