### PR TITLE
Feat: support switching from other IME

### PR DESCRIPTION
**Pull request by InfinityLoop1308**
#### Feature
Support switching from other IME.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
```
android:supportsSwitchingToNextInputMethod

Set to true if this input method supports ways to switch to a next input method (for example, a globe key.).
```

It's switch **to** not from, Trime doesn't support switch to next input method?

**Comment by InfinityLoop1309** [comment]
> ```
> android:supportsSwitchingToNextInputMethod
> 
> Set to true if this input method supports ways to switch to a next input method (for example, a globe key.).
> ```
> 
> It's switch **to** not from, Trime doesn't support switch to next input method?

this description is misdeading. I recommend you to try it by yourself.

E.g. between android default aosp keyboard and Trime
Before: You can switch from trime to aosp but not aosp to trime.
Now: both is doable

**Comment by InfinityLoop1308** [comment]
> ```
> android:supportsSwitchingToNextInputMethod
> 
> Set to true if this input method supports ways to switch to a next input method (for example, a globe key.).
> ```
> 
> It's switch **to** not from, Trime doesn't support switch to next input method?

this description is misleading. I recommend you to try it by yourself.

E.g. between android default aosp keyboard and Trime
Before: You can switch from trime to aosp but not aosp to trime.
Now: both is doable

Note: this is not describing the action of calling "change input method" menu.

**Comment by Bambooin** [comment]
Ok, it needs more code review by others.

It will be nice if you can create a new issue which decribes it and links to here.

**Comment by momobobe** [comment]
> Trime doesn't support switch to next input method?

Excuse me, but I just couldn't find how to switch to other input methods from Trime in the recent versions. Previously (before 3.2.2 or sure, don't remember), long press 123 (菜单)
and there was an option to switch input method, but now the option gets removed and I haven't found any other other button for switching. Could you plz tell me how to make it?

**Pull request merged**
