### PR TITLE
General Optimization

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
- make sure to build opencc dictionaries in the user data dir
- show schema name instead of schema id in the schema picker
- don't use librime's API to get the user data dir
- fix: temporary ascii mode set by keyboards doesn't take effect

#### Feature
Main features:
- (dev) Establish C++ class to better manage and utilize the APIs.
- (dev) Utilize the ksp to generate key mapping to help convert between Rime KeyVal and Android KeyCode.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by tao659** [comment]
这个版本选词有问题，第二页及后面的词 有时候点击会选成第一页的词，

**Comment by WhiredPlanck** [comment]
> 这个版本选词有问题，第二页及后面的词 有时候点击会选成第一页的词，

已复现，等待修复

**Comment by WhiredPlanck** [comment]
@tao659 已修复

**Comment by WhiredPlanck** [comment]
@Bambooin This PR is also ready for review.

**Pull request merged**
