### PR TITLE
优化设置引导

### PR DESCRIPTION
**Pull request by tumuyan**
## Pull request

1.  由于Trime初始化需要耗费时间，此过程UI是卡死的，故把引导中的“完成”改为“在忙..."，提醒用户不要继续操作
2.  初始化结束后，自动退出引导
3.  去除了一些无用代码

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
4. Manual build and test pass
5. GitHub action ci pass
6. At least one contributor reviews and votes
7. Can be merged clean without conflicts
8. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Some advices:
1. remove the commented code line
2. `在忙...` ==> `初始化中...`?
3. `启动` ==> `初始化`?
4. `Rime is initializing, please wait a few seconds` ==> `Rime is setting up, please wait...`?
5. `Initialize finish` ==> `Done`?
6. `name="space"` ==> add translatable="false"?

**Comment by tumuyan** [comment]
> * remove the commented code line
> * `在忙...` ==> `初始化中...`?

初始化中占用的空间有些大，在UI的视觉上左右不平衡，我觉得还是在忙/busy比较合适

下边这些我准备移除

> * `启动` ==> `初始化`?
> * `Rime is initializing, please wait a few seconds` ==> `Rime is setting up, please wait...`?
> * `Initialize finish` ==> `Done`?
> * `name="space"` ==> add translatable="false"?

**Comment by Bambooin** [comment]
Still feel unnatural with `在忙...`

**Comment by tumuyan** [comment]
或者改为 稍等？然后英文呢？

另外我在想是否应该把权限申请，用户路径设置也放到引导里？

**Comment by Bambooin** [comment]
What about `初始化中...` and `Setting up...`?

**Comment by tumuyan** [comment]
可以对照一下，我感觉不是很平衡，但是也不是不行

image

image



image

image

**Comment by Bambooin** [comment]
What happens when user clik `Skip` or `Prev` button when the Rime is setting up?

I thought `Busy...` is show on the alert dialog, but it show on the button.

Original alert dialog for waiting something is better than the button?

Alert dialog tell people must wait for something, user can't do anything.

**Comment by tumuyan** [comment]
> What happens when user clik `Skip` or `Prev` button when the Rime is setting up?

由于初始化并非在后台进程运行，事实上选择trime后UI是卡死的，点击的动作不会触发任何事情。这也是我为什么要添加这样的信息——UI卡死了，得让用户知道。
同样因为UI卡死了，甚至无法正常toast消息。

我也尝试过显示一个警告窗，或者把引导界面的“完成”改为等待的提示，这同样有些问题，并且这会破坏原有的架构设计。你可以试一下能否更好地显示警告信息。

**Comment by Bambooin** [comment]
Fine, but `在忙...` is too confusion for user, do we have better words to tell user what's going on?

**Comment by tumuyan** [comment]
从效果看，“初始化中..."的影响不是很大，可以在“跳过”的右侧加一个空字符来调整。”Setting up...“造成的偏移就有些多了。

另外目前按键按键事件调用的流程很长，也存在一些bug，比如同文风主题如下的选择键是失效的。
`  Shift_L2: {label: 选择, preview: '⇪', functional: false, send: Shift_L}`
我能否添加一些  //Key开头的特殊标记的注释，来标记重要的方法，以便持续改进？

类似如下的样子：
```
    //KeyboardEvent 处理软键盘事件
    override fun onEvent(event: Event?) {

```
```
  /**
   * 處理實體鍵盤事件
   *
   * @param event {@link KeyEvent 按鍵事件}
   * @return 是否成功處理
   */

  //KeyEvent 处理实体键盘事件
  private boolean onKeyEvent(@NonNull KeyEvent event) {

```

**Comment by Bambooin** [comment]
`BOOTING...` is short, but not good as `SETTING UP...`?

Add `TODO` comment for todo list, many IDE support it?

**Comment by mitnk** [comment]
Since it's a hint, not an action. Thus it should not show on a button. It should be showed in the middle of the screen? Then the width issue will be gone.

**Pull request closed without merging**
