### PR TITLE
Improvement for logging

### PR DESCRIPTION
**Pull request by WhiredPlanck**
## Issue tracker
Fixes:
- changing color scheme may not work

## Feature
- use seekbardialog to set clipboard and draft limit (clearing data may be required)
- enable native logging
- improve performance of LogView
- show warning or error log info when deploy from the main setting page

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

## Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

## Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
Preview

[log2.webm](https://user-images.githubusercontent.com/47623588/198010762-0b49bf24-ead5-45ae-9bd4-2d6429355008.webm)

**Comment by Bambooin** [comment]
I think we should use https://github.com/google/glog with [librime upstream](https://github.com/rime/librime/blob/f7a456937802d063a781baf37c8698cd6d6b305e/.gitmodules#L1-L3) instead of outdated `minilog` repo.

**Comment by WhiredPlanck** [comment]
> I think we should use https://github.com/google/glog with [librime upstream](https://github.com/rime/librime/blob/f7a456937802d063a781baf37c8698cd6d6b305e/.gitmodules#L1-L3) instead of outdated `minilog` repo.

I have no idea actually. @iovxw 's fork contains a patch that fixes a FTBFS problem, and since librime actually just requires a few things from `glog` to print its logs, may be the `miniglog` is just enough ......

**Comment by Bambooin** [comment]
We should follow the choice of upstream in my personal opinion.

Lots of issues found in upstream about logging.

https://github.com/rime/librime/search?q=glog&type=issues
https://github.com/rime/librime/issues/254

**Comment by WhiredPlanck** [comment]
> We should follow the choice of upstream in my personal opinion.
> 
> Lots of issues found in upstream about logging.
> 
> https://github.com/rime/librime/search?q=glog&type=issues [rime/librime#254](https://github.com/rime/librime/issues/254)

Yeah, but I'm stupid for hacking C++ stuffs ...... Need some examples to make it ......

**Comment by WhiredPlanck** [comment]
@Bambooin I've search the a lot of git repos and found that few Android projects (directly) incorporate glog into them ...... expect React Native.

**Comment by WhiredPlanck** [comment]
@Bambooin After doing so research, it seems that `glog` may not be able to build on Android natively and we may still need `miniglog`.

**Comment by WhiredPlanck** [comment]
@Bambooin Finally I make it, time to go bed anyway ~

**Comment by WhiredPlanck** [comment]
@Bambooin It seems that `glog` still cannot be complied on arm* architectures, but now I have no idea about it at all ……

**UPDATE**：Android NDK doesn't provide `backtrace` on ARM* architectures

**Comment by Bambooin** [comment]
Thanks for your hard work, but please **take care of yourself**, don't work after midnight.

As for this pull reqeust, I think we should hold on and wait for a work around later.

**Comment by WhiredPlanck** [comment]
> Thanks for your hard work, but please take care of yourself, don't work after midnight.
>
> As for this pull reqeust, I think we should hold on and wait for a work around later.

Thanks, I will ~ I am just a little obsessive about it.

And good news! glog v0.6.0 can be built without the `backtrace` problems (see https://github.com/google/glog/commit/396558472185d1796604e42a3ba458e29a60f25b). We may need to urge the upstream to update it.

**UPDATE**: a PR related this has been created: https://github.com/rime/librime/pull/578

**Comment by WhiredPlanck** [comment]
@Bambooin It seems that https://github.com/rime/librime/pull/578 is blocked by the build check failure on Windows, but I have no idea to fix it since it seems to be not issue related to glog. May you help or we just backport the changes for a while until the upstream merge them? 

**UPDATE**: I have fixed all the problems at https://github.com/rime/librime/pull/578/commits/5959e3c6533e6faaab29585b568d7b2986718590, now just wait the upstream to merge it.

**Comment by WhiredPlanck** [comment]
@Bambooin All things have been done here. I think we can merge them.

**Pull request merged**
