### PR TITLE
chore: update build guide

### LINKED ISSUE #771: Improve self-build guide
**Is your feature request related to a problem? Please describe.**
Trime is **extremely hard** to build for those who are not very familiar to this project. 
Last time I spent almost a whole week to make it worked, and after I deleted some files by mistake yesterday,  it began to fail building. I spent several hours trying to fix it, but no approaches works.
When a cpp dependency throw an error, it is almost IMPOSSIBLE for non-cpp-developers to find a way to fix. I have encountered errors from boost, librime, libiconv, and capnp for no reason. No guides are given. Some were solved luckily, but everything breaks once you are unfortunate.

**Describe the solution you'd like**
I don't know if there is a way to avoid complex cmake procedure for dependencies, but at least there should be more guidance to help solving building errors.

**Describe alternatives you've considered**
A standardized building procedure may be given.

**Additional context**

### PR DESCRIPTION
**Pull request by InfinityLoop1308**
#### Issue tracker
Fixes will automatically close the related issue

Fixes #771 

#### Feature
Describe feature of pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
What about add command in Makefile?

```
clean:
	rm -rf build app/build app/.cxx/
	./gradlew clean
```

So we can clean it with `make clean`.

**Comment by Bambooin** [comment]
Actually we have three README files, so we should update them together.

The `capnp` package can be installed from package manager, such as: `brew`

```
brew pin capnp
```

If we update `capnp` module, user have to recompile it from source, it's waste of resoure and time.
`If you would like to test the application, run:` ==> `Debug version without sign`?

Some of words should be polished for README?

**Comment by InfinityLoop1308** [comment]
> The `capnp` package can be installed from package manager, such as: `brew`
> 
> ```
> brew pin capnp
> ```
> 

 Can confirm this solution not work for yum/dnf.

**Comment by InfinityLoop1308** [comment]
> `If you would like to test the application, run:` ==> `Debug version without sign`?
> 
> Some of words should be polished for README?

Any other changes? I will make this change in the next commit.

**Comment by InfinityLoop1308** [comment]
> > The `capnp` package can be installed from package manager, such as: `brew`
> > ```
> > brew pin capnp
> > ```
> 
> Can confirm this solution not work for yum/dnf.


Actually that is why I mention 
> Do not install capnp from package-manager or other sources

in my troubleshooting. They simply do not work.

**Pull request merged**
