### PR TITLE
Drop AndroidUtilCode

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

This PR is going to drop [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode) because it is in poor maintenance,  and as a large util collection, we're only using 5% of its capabilities. So I decide to re-implement the function that we're using, then drop the dependency, this may also reduce the app size.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Found one crash when keyboard pop up:
```
--------- Build Info
Package Name: com.osfans.trime
Builder: (Unknown)
Version Code: 20240701
Version Name: v3.2.18-46-g0685959c-release
Build Time: 2024-06-14T06:33:17Z
Build Git Hash: 0685959ce4ecb2c0bf9ebf3fb0f30b0315d4868a
--------- Crash stacktrace
java.lang.ExceptionInInitializerError
	at com.osfans.trime.ime.keyboard.KeyboardSwitcher.newOrReset(KeyboardSwitcher.kt:41)
	at com.osfans.trime.ime.core.TrimeInputMethodService.recreateInputView(TrimeInputMethodService.kt:316)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1$1.invokeSuspend(TrimeInputMethodService.kt:431)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1$1.invoke(Unknown Source:8)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1$1.invoke(Unknown Source:4)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invokeSuspend(RimeDaemon.kt:65)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invoke(Unknown Source:8)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invoke(Unknown Source:4)
	at com.osfans.trime.core.RimeLifecycleKt.whenAtState(RimeLifecycle.kt:86)
	at com.osfans.trime.daemon.RimeDaemon$establish$1.runOnReady(RimeDaemon.kt:157)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1.invokeSuspend(TrimeInputMethodService.kt:430)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7522704, Dispatchers.Main]
Caused by: java.lang.IllegalArgumentException: No enum constant com.osfans.trime.data.AppPrefs.Keyboard.SplitOption.never
	at java.lang.Enum.valueOf(Enum.java:259)
	at com.osfans.trime.data.AppPrefs$Keyboard$SplitOption.valueOf(Unknown Source:2)
	at com.osfans.trime.data.AppPrefs$Keyboard.getSplitOption(AppPrefs.kt:212)
	at com.osfans.trime.ime.keyboard.KeyboardPrefs.isLandscapeMode(KeyboardPrefs.kt:17)
	at com.osfans.trime.ime.keyboard.KeyboardSwitcher.switchKeyboard(KeyboardSwitcher.kt:90)
	at com.osfans.trime.ime.keyboard.KeyboardSwitcher.newOrReset(KeyboardSwitcher.kt:46)
	at com.osfans.trime.ime.keyboard.KeyboardSwitcher.<clinit>(KeyboardSwitcher.kt:36)
	... 21 more
```

**Comment by WhiredPlanck** [comment]
@Bambooin Sorry for forgetting to remind that you need to reconfigure “Change to landscape keyboard” in “Keyboard settings” in the app.

**Comment by Bambooin** [comment]
Failed with same error after reinstallation, this should be fixed for new installtion.

Or the new user can't use Trime, unless them reconfigure the specific item in the setting.

**Comment by WhiredPlanck** [comment]
> Failed with same error after reinstallation, this should be fixed for new installtion.
> 
> Or the new user can't use Trime, unless them reconfigure the specific item in the setting.

Reinstalling without uninstalling first cannot fix this issue, or you can clear the app data in the system settings page, the essence of this is to reset the value of the corresponding SharedPreference.

**Comment by Bambooin** [comment]
I had **uninstaled** the Trime and reinstalled, to simulate the case for the new user.

So the new users will have this issue too, which should be fixed.

**Comment by WhiredPlanck** [comment]
> I had **uninstaled** the Trime and reinstalled, to simulate the case for the new user.

Weird. I'll take a look.

**Comment by WhiredPlanck** [comment]
https://github.com/osfans/trime/pull/1400/commits/99ce17ba7e4ff6b4bd14d4699809f1c497a04b49 may fix this issue.

**Review by Bambooin — APPROVED** [review]
The issue was fixed with the latest patch.

**Pull request merged**
