### PR TITLE
Theme Parsing Tweaking

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issue

Fixes ... I don't remember :rofl: 

#### Feature
This PR is mainly to tweak the process of parsing the theme to speed it up and shrink the code to make it easier to maintain in the future.
See the commits for detail.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
## Known regressions
- ~~The switch used to toggle ascii mode on the bar actually doesn't take effect, when you press the key after toggling, it jump back to the last state. ( But the switch beside the space bar works)
  **UPDATE**: The real issue is that the switch actually toggles the state to the opposite one as it shows, and so does all other switches on the bar, according to the log. For example, when you see the switch toggles the ascii mode as true, it actually toggles it as false, and vice versa.~~
  (Fixed at 272cbdc)

**Comment by WhiredPlanck** [comment]
@Bambooin All done finally.

**Comment by Bambooin** [comment]
Found one crash with steps:
1. Theme & Color
2. Themes
3. Switch to another theme
4. Crash(90%)

**Comment by WhiredPlanck** [comment]
> Found one crash with steps:
> 
>     1. Theme & Color
> 
>     2. Themes
> 
>     3. Switch to another theme
> 
>     4. Crash(90%)

Reproduced. Interesting thing is that because the log is too massive to see the error exactly, I increase the log level librime outputted and find that the app never crash again ……

**Comment by WhiredPlanck** [comment]
@Bambooin 896743b works for me. It may work for you too.

**Comment by Bambooin** [comment]
Crashing when switch theme with **latest commit** in Android 11.

**Comment by WhiredPlanck** [comment]
> Crashing when switch theme with **latest commit** in Android 11.

I think I find the true reason, this is actually mentioned and fixed in #877 . The picker immediately initialize the keyboard to let the theme take effect, which is a UI operation, it must be putted in the main thread to run. You may need to make a decision that whether to merge #877 or let me fix in this PR.

**Comment by Bambooin** [comment]
Thanks for your hard work, I had cherried pick #877 into your branch, and remove your last commit.

**Comment by WhiredPlanck** [comment]
@Bambooin Thanks ~

**Pull request closed without merging**
