### PR TITLE
API Refactors (20240627)

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by Bambooin** [comment]
Found two issues in local build with `make release`

1. The make `style-lint` error in `app/src/main/jni/librime_jni/rime_jni.cc`
2. The Trime crash during inputing

**Comment by WhiredPlanck** [comment]
> 1. The make `style-lint` error in `app/src/main/jni/librime_jni/rime_jni.cc`

Fixed.

> 2\. The Trime crash during inputing

Cannot reproduce. Any log there?

**Comment by Bambooin** [comment]
No log found, the Trime crashes when I click the keyboard.

Steps for the build:
```
make clean
make release
```

**Comment by WhiredPlanck** [comment]
> No log found, the Trime crashes when I click the keyboard.
> 
> Steps for the build:
> 
> ```
> make clean
> make release
> ```

That's weird. I do the steps so but end up with no problem.

**Comment by WhiredPlanck** [comment]
@Bambooin Sorry, I need to go on a business trip this week, so I won't have time to modify the code.

**Comment by WhiredPlanck** [comment]
Close for issues that are difficult to fix.

**Pull request closed without merging**
