### PR TITLE
UI improvement survey 20220904

### PR DESCRIPTION
**Pull request by WhiredPlanck**
## Issue tracker
- fix(data): should list sound profiles in the subdir
- fix(ui): the buttons in the navigation bar are difficult to see
- fix(ui/data): try to fix hardcoded data dir (#823)
- fix(ui): navigation bar overlaid the last preference

## Feature

- ~~chore: add leakcanary dependency (#839)~~
- chore: remove redundant items in manifest
- chore: add junit test implementations
- refactor(data): remove unused functions in Config.java
- chore: polish methods to get custom build config fields
- chore: update gradle build tools plugin to 7.2.2
- refactor(ui): improve how to show license page
- feat(ui): add animation when navigate between the fragments
- refactor(ui): polish LiquidKeyboardActivity
- refactor(ui): reorder preferences in OtherFragment
- refactor(ui): fine tune DialogSeekBarPreference

## Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

## Gradle task
Tasks passed on every commit
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembleDebug`

#### Manual test
- [x] Done

## Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

## Daily build
Login to fetch artifact

https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
Preview: 

uis

**Comment by WhiredPlanck** [comment]
@Bambooin @tumuyan This PR is ready for review.

**Comment by Bambooin** [comment]
Verified that #823 fixed, I had used it since yesterday.

**Comment by WhiredPlanck** [comment]
> Verified that #823 fixed, I had used it since yesterday.

Great ~ Happy to hear that.

**Comment by WhiredPlanck** [comment]
@Bambooin Currently I have dropped commit bcd1431 in this PR, so we can just focus on the topic here.

**Pull request merged**
