### PR TITLE
Unrolled Candidates (20240901)

### PR DESCRIPTION
**Pull request by WhiredPlanck**
#### Issue tracker
Fixes will automatically close the related issues

Fixes # N/A

#### Feature
Describe features of this pull request

Finally it's coming up! The modern candidate selecting experience for smartphone is now here.

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [x] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
Preview

https://github.com/user-attachments/assets/c294f5db-775b-4129-b520-42aa0a72a86d

**Comment by WhiredPlanck** [comment]
Preview 2

https://github.com/user-attachments/assets/546b1a66-b7f1-49a7-ad96-ef8fd986c408

**Review by Bambooin — APPROVED** [review]
LGTM, no issues found during manually testing, seems we can collect feedback from community(QQ and Telegram).

Thanks for your hard work for this useful feature.👍

The new release will be delayed to today later after feedback from community.

**Comment by WhiredPlanck** [comment]
> LGTM, no issues found during manually testing, seems we can collect feedback from community(QQ and Telegram).
> 
> Thanks for your hard work for this useful feature.👍
> 
> The new release will be delayed to today later after feedback from community.

Thank you ~ I will collect the feedback then put here.

**Comment by WhiredPlanck** [comment]
@Bambooin Twice force push to fix typos, never mind ~

**Comment by goofyz** [comment]
Good work!
Candidate view works without problem.

However, "shift" does not work in "Ascii off" mode now. (It works in "Ascii on now).

**Pull request merged**
